### PR TITLE
Fixed #1462.

### LINKED ISSUE #1462: Sub-panels are not displayed on Event Detail's Panel
Subj.
ver. 7.6.3 on sdemo.suiteondemand.com

apache error.log:

PHP Warning:  Illegal offset type in isset or empty in /include/generic/SugarWidgets/SugarWidgetSubPanelTopButton_c.php on line 153,
PHP Catchable fatal error:  Object of class LayoutManager could not be converted to string in /include/generic/SugarWidgets/SugarWidgetSubPanelTopButton_c.php on line 254

### PR DESCRIPTION
**Pull request by MikeyJC**
Fix fatal on delegates subpanel in event module detail view.

### CODE REVIEW

File: include/generic/SugarWidgets/SugarWidgetSubPanelTopButton_c.php [hunk 1]
```diff
@@ -251,9 +251,11 @@ function &_get_form($defines, $additionalFormFields = null, $asUrl = false)
             $form = 'form' . $relationship_name;
             $button = '<form action="index.php" method="post" name="form" id="' . $form . "\">\n";
             foreach($formValues as $key => $value) {
-                $button .= "<input type='hidden' name='" . $key . "' value='" . $value . "' />\n";
+                if (empty($value->defs)) {
+                    $button .= "<input type='hidden' name='" . $key . "' value='" . $value . "' />\n";
+                }
             }
-
+
```
Comment (samus-aran) [inline include/generic/SugarWidgets/SugarWidgetSubPanelTopButton_c.php]: Can you remove this space - it's not necessary
