### PR TITLE
Fix bugged opt-in flag change

### LINKED ISSUE #5901: Converting Lead to Contact doesn't preserve Confimrer-Opt-In status
When, with confirmed-opt-in Email status is converted to Contact, created contact Email confirmet-op-tin status is changed back to opt-in (and this action is even not loged in email_adresses_audit table.

#### Issue
- Lead Confirm Opt-In options
- Convert Lead to Contact
- Contact's Email is now in status Opt-In instead confirmed-opt-in

#### Expected Behavior
After convering Lead with confimred opt-in email Contact should keep Email status as it is.

#### Actual Behavior
Email of converted Contact is in status Opt-In and action of change is not loged in audit table.

#### Steps to Reproduce
1. Have Lead with Confirmed Email
2. Select Action/Convert
3. Converted Contact's Email is now in opt-in status

### PR DESCRIPTION
**Pull request by PedroErnst**
Fixes a bug where $optInFlag was being set to 0 in every case.

## Description

Fixes #5901 

## How To Test This

1. Have Lead with Confirmed Email
2. Select Action/Convert
3. Converted Contact's Email is still confirmed opt in
4. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

File: include/SugarEmailAddress/SugarEmailAddress.php [hunk 1]
```diff
@@ -1249,7 +1249,7 @@ public function AddUpdateEmailAddress($addr, $invalid = 0, $opt_out = 0, $id = n
 
         // confirmed opt in check
         if (!is_null($optInFlag)) {
-            $optInFlag = 0;
+            $optInFlag = (int)$optInFlag;
```
Comment (zoltankocsardi) [inline include/SugarEmailAddress/SugarEmailAddress.php]: If you convert the value to integer here, converts below this line are not necessary.
