### PR TITLE
Fixed #2094 iCal now export VTODO and no VEVENT

### LINKED ISSUE #2094: iCal now export VTODO and no VEVENT
#### Issue
When exporting with iCal, the ics file now contains VTODO but no VEVENT anymore. So the calendar is not exported

#### Expected Behavior
Export Meetings

#### Actual Behavior
Export Tasks

#### Steps to Reproduce
1. Get the ics file with http://YOURSERVER/ical_server.php?type=ics&key=xxxx&email=yyyy@zzz.com
2. Check the ics file

#### Your Environment

* SuiteCRM Version used: 7.7.2, migrated from 7.5

### PR DESCRIPTION
**Pull request by shogunpol**
iCal now export VTODO and no VEVENT
## Description
iCal now export VTODO and no VEVENT
References to bug #2094

Changes has been made with contribution of @chandon.
Thanks for contribution.
iCal now export VTODO and no VEVENT

Get the ics file with http://YOURSERVER/ical_server.php?type=ics&key=xxxx&email=yyyy@zzz.com
Check the ics file

## Motivation and Context

Fixed iCal export VTODO and no VEVENT
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by chandon** [comment]
@shogunpol thanks

File: config_override.php [hunk 1]
```diff
@@ -1,3 +1,8 @@
 <?php
 /***CONFIGURATOR***/
+$sugar_config['enable_action_menu'] = true;
```
Comment (mattlorimer) [inline config_override.php]: shouldn't be here

File: modules/iCals/iCal.php [hunk 2]
```diff
@@ -214,7 +214,25 @@ protected function createSugarIcal(&$user_bean,&$start_date_time,&$end_date_time
...
+                "end" => "date_end"
+            ),
+            "Calls" => array(
+                "showCompleted" => true,
+                "start" =>  "date_start",
+                "end" => "date_end"
+            ),
+            "Tasks" => array(
+                "showCompleted" => true,
+                "start" =>  "date_start",
```
Comment (mattlorimer) [inline modules/iCals/iCal.php]: tasks uses 'date_due' for the "start and "end" date
