### PR TITLE
Fixed #2225 - My-activity-stream-options-generates-error

### LINKED ISSUE #2225: My-activity-stream-options-generates-error
I cannot access the my activity streams options.
It gives a small 1 line box on the screen.

 PHP Warning: Smarty error: unable to read resource: "custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl" in /www/html/suitecrm/include/Smarty/Smarty.class.php on line 1094

There is a small workaround that was proposed on the forum:
https://www.suitecrm.com/forum/suitecrm-7-0-discussion/8570-my-activity-stream-options-generates-error#38042

My version is 7.7.4 (but it was reported also for the previous versions) on IIS/MySql

### PR DESCRIPTION
**Pull request by shogunpol**
Fixed My-activity-stream-options-generates-error
## Description

Fixed My-activity-stream-options-generates-error

Referenced issue #2225 

## Motivation and Context

Fixes My-activity-stream-options-generates-error
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php [hunk 1]
```diff
@@ -419,7 +419,7 @@ function displayOptions() {
 			$ss->assign('autoRefreshSelect', $this->autoRefresh);
 		}
 
-        return  $ss->fetch('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');
+        return  $ss->fetch(get_custom_file_if_exists('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl'));
```
Comment (mattlorimer) [inline modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php]: with get_custom_file_if_exists you should pass in the name of the file

Comment (shogunpol) [inline modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php]: @mattlorimer , I assume, you mean 'should not pass', and its fixed
