### PR TITLE
Fix #5385 - Fix Closed survey issues

### LINKED ISSUE #5385: A Closed survey issues
default

1. Survey  logo is not displayed - file modules/Surveys/Entry/survey_logo.jpg does not exist
2. Survey  message is hard coded: https://github.com/salesagility/SuiteCRM/blob/master/modules/Surveys/Entry/Survey.php#L366

See also #4646

#### Your Environment

* SuiteCRM Version used: 7.10

### PR DESCRIPTION
**Pull request by serhiisamko091184**
Issue:
https://github.com/salesagility/SuiteCRM/issues/5385
[#4800](https://github.com/salesagility/SuiteCRM/issues/4800)

## Description

1. Added a src to use the same picture as if the Survey in status "Public".
image

2. Added a new label to language file to effectively substitute hard coded string. 

## Motivation and Context

To make Suite Application cleaner (usage of labels instead raw strings + fix of broken image)

## How To Test This

1. Create Survey;
3. Change status of created Survey to "Closed";
4. Try to access the Survey through EntryPoint with ID of your Survey as it described in the initial issue. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Surveys/Entry/Survey.php [hunk 1]
```diff
@@ -378,13 +378,17 @@ function displayClosedPage($survey)
     <div class="container">
         <div class="row">
             <div class="col-md-offset-3 col-md-6">
-                <img height=100 src="modules/Surveys/Entry/survey_logo.jpg"/>
+                <img src="themes/default/images/company_logo.png"/>
```
Comment (clemente-raposo) [inline modules/Surveys/Entry/Survey.php:381]: Hi @serhiisamko091184, I imagine this supposed to change if the user changes the system logo. This needs to be dynamically calculated. Plus it should also take into consideration the theme that is being used by the user.

File: modules/Surveys/Entry/Survey.php [hunk 2]
```diff
@@ -378,13 +378,17 @@ function displayClosedPage($survey)
     <div class="container">
```
Comment (clemente-raposo) [inline modules/Surveys/Entry/Survey.php:378]: Hi @serhiisamko091184, also, maybe better to have this full html code on a template instead of doing it by breaking the php tags.

File: modules/Surveys/Entry/Survey.php (hunk 1 above)
Comment (serhiisamko091184) [reply modules/Surveys/Entry/Survey.php]: Hey @clemente-raposo ,
thanks for feedback, 
done.

**Review by johnM2401 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]
