### PR TITLE
Fixed #3853 - fix reply-to checkbox

### LINKED ISSUE #3853: In user profile doesn't save the "Reply to" checkbox + doesn't change email value in FROM (in compose email pop up)
#### Issue

I set up in offical demo 7.9.2 the primary and reply to fields 

user1

I pressed save button and after again edited the user info

user2

The value for Reply to is not saved 

+ if you compose email.. you will have not as first value the choosed primary email.. this is not working for new email in 7.9.x as worked in 7.8.x

#### Expected Behavior

Will save value for reply to email address
Will see the primary email address in compose emial pop up as default/primary FROM email 👍 

#### Your Environment

* SuiteCRM Version used: Official 7.9.2

### PR DESCRIPTION
**Pull request by gymad**
## Description

Fixed #3853 - fix reply-to checkbox

## Motivation and Context

please see in related issue: #3853
## How To Test This

please see in related issue: #3853
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js [hunk 1]
```diff
@@ -298,7 +298,7 @@
       // Reply to checkbox
       var replyToCheckbox = lineContainer.find('input#email-address-reply-to-flag');
       if (replyToCheckbox.length == 1) {
-        replyToCheckbox.attr('name', this.module + _eaw.id + '"emailAddressReplyToFlag');
+        replyToCheckbox.attr('name', this.module + _eaw.id + 'emailAddressReplyToFlag');
```
Comment (daniel-samson) [inline jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js]: :+1:
