### PR TITLE
loadUserOnLogin compatible with SugarAuthenticateUser::authenticateUser

### LINKED ISSUE #3442: LDAPAuthenticateUser not compatible with SugarAuthenticateUser::loadUserOnLogin
Enabling LDAP Authentication causes an warning message in logs. This warning floods the error logs with the message. 

#### Issue

When LDAP Authentication is enable the following error is generated in apache error logs:
`
PHP Warning:  Declaration of LDAPAuthenticateUser::loadUserOnLogin($name, $password) should be compatible with SugarAuthenticateUser::loadUserOnLogin($name, $password, $fallback = false, $PARAMS = Array) in /var/www/html/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 52, referer: https://crm.cobra.local/index.php?module=Users&action=Login
`
#### Expected Behavior

LDAPAuthenticateUser::loadUserOnLogin be compatible with SugarAuthenticateUser::loadUserOnLogin and not generate the warning. 

#### Actual Behavior

LDAPAuthenticateUser::loadUserOnLogin is  not compatible with SugarAuthenticateUser::loadUserOnLogin and generates warnings in error logs.
#### Possible Fix

LDAPAuthenticateUser::loadUserOnLogin signature be consistent with SugarAuthenticateUser::loadUserOnLogin. 

#### Steps to Reproduce

1. Enable LDAP Authentication
2. Enable Stack trace or watch apache error logs
3. Login with an ldap user

#### Context

Main issues is it generates many entries in the Apache error logs, and can be easily fixed. It does not appear to affect functionality.  It is a low priority issue. 

#### Your Environment

* SuiteCRM Version used 7.8.3
* Chrome Version 56.0.2924.87 (64-bit)
* MySQL, PHP 7
* Ubuntu 16.04

### PR DESCRIPTION
**Pull request by LEAP-nishit**
Makes  LDAPAuthenticateUser::authenticateUser compatible with  SugarAuthenticateUser::authenticateUser. 
## Description

This resolves #3442. 

## How To Test This

Enable LDAP and check is any stack traces are generated due to authentication. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php [hunk 1]
```diff
@@ -280,11 +281,13 @@ function createUser($name){
...
-	 * @param STRING $name
-	 * @param STRING $password
+	 * @param string $name
+	 * @param string $password
+	 * @param boolean $fallback - is this authentication a fallback from a failed authentication
+	 * @param array $PARAMS
 	 * @return boolean
 	 */
-	function loadUserOnLogin($name, $password) {
+	function loadUserOnLogin($name, $password, $fallback = false, $PARAMS = array()) {
```
Comment (daniel-samson) [inline modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php]: PSR 2: $PARAMS all capitals. This should be camel case like "$params".

**Comment by LEAP-nishit** [comment]
Thanks @daniel-samson , mades the change as suggested.
