### PR TITLE
Fix #9725 - Date field value isn't saved in a Workflow action related module

### LINKED ISSUE #9725: Date field value isn't saved in a Workflow action related module
When assigning a value to a date field of a related module in an action of a Workflow, the value isn't saved properly. After Saving and Editing, the value is gone.
wfemptydate

#### Issue

Date field value isn't saved in a Workflow action related module

#### Expected Behavior

The vlaue should besaved

#### Actual Behavior

The value dissappears

#### Possible Fix

fixUpFormating function from Workflow doesn't identify the module and the field type. Therefore it formats the value, ending up erasing its content.

#### Steps to Reproduce

1. Create a Workflow based in Accounts
2. Add an action that modifies the record
3. Add the Birthdate field from the Contacts::Contacts relationship
4. Assign a value to the date field
5. Save the WF
6. Edit again de WF and check that the value has gone.

#### Context

This is troublesome when an user wants to modify fields from related records

#### Your Environment

SuiteCRM Version used: Version 7.12.6
Browser name and version: Versión 100.0.4896.88 (Build oficial) (64 bit
Environment name and version: MySQL, PHP 7
Operating System and version: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by SinergiaCRM**
- Closes #9725 

## Description
This PR adds code to retrieve the module name that contains the selected field value. Then it provides the module name to the function fixUpFormatting().

## Motivation and Context

Format the value properly.

## How To Test This

1. Create a Workflow based in Accounts
2. Add an action that modifies the record
3. Add the Birthdate field from the Contacts::Contacts relationship
4. Assign a value to the date field
5. Save the WF
6. Edit again de WF and check that the value stays.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/AOW_Actions/AOW_Action.php [hunk 1]
```diff
@@ -107,7 +107,18 @@ public function save_lines($post_data, $parent, $key = '')
                                 if ($post_data[$key . 'param'][$i]['value_type'][$p_id] == 'Value' && is_array($p_value)) {
                                     $param_value[$p_id] = encodeMultienumValue($p_value);
                                 }elseif($post_data[$key . 'param'][$i]['value_type'][$p_id] == 'Value'){
-                                    $param_value[$p_id] = fixUpFormatting($params["record_type"], $post_data[$key . 'param'][$i]["field"][$p_id], $p_value);
+                                    if (isset($params['rel_type']) && !empty($params['rel_type']) && ($params['rel_type'] != $params['record_type'])) {
```
Comment (clemente-raposo) [inline modules/AOW_Actions/AOW_Action.php:110]: Hi @SinergiaCRM, thank you for your PR.

Could we use `!==` instead of `!=` in `$params['rel_type'] != $params['record_type'])`?

Comment (SinergiaCRM) [reply modules/AOW_Actions/AOW_Action.php]: Done!

**Review by jack7anderson7 — APPROVED** [review]

File: modules/AOW_Actions/AOW_Action.php (hunk 1 above)
Comment (clemente-raposo) [reply modules/AOW_Actions/AOW_Action.php]: Thank  you @SinergiaCRM

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by johnM2401 — APPROVED** [review]
Thank you for your PR @SinergiaCRM !

I've done some testing on this, and it appears to largely resolve the issues found.

However, I've noticed one edge-case in which the Date/time Values are lost:

It appears that, if the user's date/time values are modified before saving the Workflow, the values are lost.

so:

- Create a Workflow, Add a Related Module's Date and Datetime field as per your initial Steps to replicate.
- Save & Re-edit the Workflow, see that the values remain.
- Open the editview of the Workflow, but do not save yet
- In another window/tab, change your user's Date & Time Preferences
- Save the Workflow
- See that the values are lost

See:
[2023-04-11 17-25.webm](https://user-images.githubusercontent.com/13675281/231228660-47075979-36b8-4c62-92a1-40657b5ebfe2.webm)

However, I feel this is a *very* uncommon edge case, so I've marked this PR as approved for the time being.

What are your thoughts, @SinergiaCRM @clemente-raposo ?
