### PR TITLE
Fixed #1253 - added a switch statement.

### LINKED ISSUE #1253: Reports "Equal to period" doesn't work as expected
If I set a date field as a parameter and have it as, for example "Equal to this quarter" I would expect this to return any records in April, May or June. However it creates the following:
`field = "2016-04-01 00:00:00"`
Which returns no results because no field has exactly this value.

### PR DESCRIPTION
**Pull request by vladbar**
Fixed #1253 - added a switch statement which adds a period instead of a plain date (if condition has Equal to preiod).

### CODE REVIEW

File: modules/AOR_Reports/AOR_Report.php [hunk 1]
```diff
@@ -1324,7 +1324,40 @@ function build_report_query_where($query = array()){
...
+                            $value = '"' . getPeriodDate($params)->format('Y-m-d H:i:s') . '"';
+
+                            switch ($app_list_strings['aor_sql_operator_list'][$condition->operator]) {
+                                case "=":
+                                    $query['where'][] = $field . ' BETWEEN ' . $value .  ' AND ' . '"' . $date . '"';
+                                    break;
+                                case "!=":
+                                    $query['where'][] = $field . ' NOT BETWEEN ' . $value .  ' AND ' . '"' . $date . '"';
+                                    break;
+                                case ">":
```
Comment (mattlorimer) [inline modules/AOR_Reports/AOR_Report.php]: > < >= <= all have the same action can they not be grouped together

File: modules/AOR_Reports/AOR_Report.php [hunk 2]
```diff
@@ -1324,7 +1324,40 @@ function build_report_query_where($query = array()){
...
+                                    break;
+                                case ">=":
+                                    $query['where'][] = $field . ' ' . $app_list_strings['aor_sql_operator_list'][$condition->operator] . ' ' . $value;
+                                    break;
+                                case "<=":
+                                    $query['where'][] = $field . ' ' . $app_list_strings['aor_sql_operator_list'][$condition->operator] . ' ' . $value;
+                                    break;
+                            }
+                        } else {
+                            $query['where'][] = ($tiltLogicOp ? '' : ($condition->logic_op ? $condition->logic_op . ' ': 'AND ')) . $field . ' ' . $app_list_strings['aor_sql_operator_list'][$condition->operator] . ' ' . $value;
```
Comment (mattlorimer) [inline modules/AOR_Reports/AOR_Report.php]: do the previous factor in the $tiltLogicOp check, should maybe be a more generic check if within !where_set

File: modules/AOR_Reports/aor_utils.php [hunk 3]
```diff
@@ -205,6 +205,80 @@ function getPeriodDate($date_time_period_list_selected)
 }
 
 /**
+ * getPeriodDate
+ * @param $date_time_period_list_selected
+ * @return DateTime
+ */
+function getPeriodEndDate($date_time_period_list_selected)
+{
+    if ($date_time_period_list_selected == 'today') {
```
Comment (mattlorimer) [inline modules/AOR_Reports/aor_utils.php]: better as a switch statement
