### PR TITLE
 Fixed #4367 - files.md5 sets $md5_string_calculated but here $md5_string used

### LINKED ISSUE #4367: files.md5 sets $md5_string_calculated but here $md5_string used
Dont know if this has any impact or if it is just deprecated, but looks wrong to me
$md5_string_calculated : https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/files.md5#L3
$md5_string : https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/ModuleInstall/ModuleScanner.php#L665

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Updates $md5_string to use $md5_string_calculated. https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/ModuleInstall/ModuleScanner.php#L665

$md5_string_calculated : https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/files.md5#L3

## Motivation and Context

Issue reference: #4367 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: ModuleInstall/ModuleScanner.php [hunk 1]
```diff
@@ -454,201 +481,241 @@ public function __construct()
...
+    }
+
+    /**
+     * Given a file it will open it's contents and check if it is a PHP file (not safe to just rely on extensions)
+     * if it finds <?php tags it will use the tokenizer to scan the file
+     * $var()  and ` are always prevented then whatever is in the blacklist.
+     * It will also ensure that all files are of valid extension types
+     *
+     */
+    public function scanFile($file)
```
Comment (gymad) [inline ModuleInstall/ModuleScanner.php]: missing phpdoc

**Comment by daniel-samson** [comment]
Assessed
