### PR TITLE
Fixed #5967 - AOR Reports - incorrect calculation for date quarter periods

### LINKED ISSUE #5967: AOR Reports - incorrect calculation for date quarter periods
In AOR Reports conditions based on on date period This Quarter or Last Quarter do not work as expected.

When the current date is in the last month of a quarter (i.e. March, June, September or December) then conditions based on date quarter periods do not work properly - causing incorrect results often returning no data rows when there should be.

I have tracked the problem in the code down to the following:-

file: aor_utils.php - function: calculateQuarters

```
function calculateQuarters($offsetMonths = 0)
{
    // define quarters
    $q = array();
    $q['1'] = array();
    $q['2'] = array();
    $q['3'] = array();
    $q['4'] = array();
    ...
    $q1end = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
    $q1end->add(new DateInterval('P2M'));

    $q2start = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
    $q2start->add(new DateInterval('P3M'));
    $q2end = DateTime::createFromFormat(DATE_ISO8601, $q2start->format(DATE_ISO8601));
    $q2end->add(new DateInterval('P2M'));

    $q3start = DateTime::createFromFormat(DATE_ISO8601, $q2start->format(DATE_ISO8601));
    $q3start->add(new DateInterval('P3M'));
    $q3end = DateTime::createFromFormat(DATE_ISO8601, $q3start->format(DATE_ISO8601));
    $q3end->add(new DateInterval('P2M'));

    $q4start = DateTime::createFromFormat(DATE_ISO8601, $q3start->format(DATE_ISO8601));
    $q4start->add(new DateInterval('P3M'));
    $q4end = DateTime::createFromFormat(DATE_ISO8601, $q4start->format(DATE_ISO8601));
    $q4end->add(new DateInterval('P2M'));
    ...
    return $q;
}
```

Suggested fix:-

```
function calculateQuarters($offsetMonths = 0)
{
    // define quarters
    $q = array();
    $q['1'] = array();
    $q['2'] = array();
    $q['3'] = array();
    $q['4'] = array();
    ...
    $q1end = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
    $q1end->add(new DateInterval('P3M'));
    $q1end->sub(new DateInterval('PT1S'));

    $q2start = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
    $q2start->add(new DateInterval('P3M'));
    $q2end = DateTime::createFromFormat(DATE_ISO8601, $q2start->format(DATE_ISO8601));
    $q2end->add(new DateInterval('P3M'));
    $q2end->sub(new DateInterval('PT1S'));

    $q3start = DateTime::createFromFormat(DATE_ISO8601, $q2start->format(DATE_ISO8601));
    $q3start->add(new DateInterval('P3M'));
    $q3end = DateTime::createFromFormat(DATE_ISO8601, $q3start->format(DATE_ISO8601));
    $q3end->add(new DateInterval('P3M'));
    $q3end->sub(new DateInterval('PT1S'));

    $q4start = DateTime::createFromFormat(DATE_ISO8601, $q3start->format(DATE_ISO8601));
    $q4start->add(new DateInterval('P3M'));
    $q4end = DateTime::createFromFormat(DATE_ISO8601, $q4start->format(DATE_ISO8601));
    $q4end->add(new DateInterval('P3M'));
    $q4end->sub(new DateInterval('PT1S'));
    ...
    return $q;
}
```

The incorrect calculation of the end date of quarters means that the getPeriodDate function fails to find the correct start date of the current or last quarter and incorrectly returns the current date instead.

Issue discovered in LTS 7.8.19 and I looked at code in the latest development release (7.10.5) and it appears to be present in this version too.

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When the current date is in the last month of a quarter (i.e. March, June, September or December) then conditions based on date quarter periods do not work properly - causing incorrect results often returning no data rows when there should be.

## Motivation and Context

Issue reference: #5967

## How To Test This

Check that a report with conditions based on on date period This Quarter or Last Quarter returns the correct results.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by willrennie** [comment]
Assessed as working, although In the hotfix 7.8.x I couldn't see major issues with this quarter/next quarter but this fix does work as expected.

File: modules/AOR_Reports/aor_utils.php [hunk 1]
```diff
@@ -342,22 +342,26 @@ function calculateQuarters($offsetMonths = 0)
...
     $q1end = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
-    $q1end->add(new DateInterval('P2M'));
+    $q1end->add(new DateInterval('P3M'));
+    $q1end->sub(new DateInterval('PT1S'));
 
     $q2start = DateTime::createFromFormat(DATE_ISO8601, $q1start->format(DATE_ISO8601));
     $q2start->add(new DateInterval('P3M'));
     $q2end = DateTime::createFromFormat(DATE_ISO8601, $q2start->format(DATE_ISO8601));
-    $q2end->add(new DateInterval('P2M'));
+    $q2end->add(new DateInterval('P3M'));
```
Comment (gymad) [inline modules/AOR_Reports/aor_utils.php]: :+1:
