### PR TITLE
Fixed #9358 - Meeting invite notification emails are not sending to all invitees.

### LINKED ISSUE #9358: Meeting invite notification emails not sending to all invitees.
#### Issue
When creating a meeting in the meetings module, the invite notification emails are only going to the first invited user/contact/lead.

#### Expected Behavior
All invitees should receive a meeting invite email

#### Actual Behavior
1 invitee is emailed.

#### Possible Fix
Check against an array of user ids rather than a boolean when preventing duplicate emails caused by workflow hooks

#### Steps to Reproduce
1. Create a meeting in the meetings module
2. Invite more than 1 user
3. Hit Save and send invites
4. Check logs or mailcatcher if set up

#### Context
Need to make sure all meeting invitees receive an invitation email.

#### Your Environment
* SuiteCRM Version used: 7.12.0
* Browser name and version: Firefox Version 94.0 (64-bit))
* Environment name and version: PHP 7.4
* Operating System and version: Ubuntu 20.04.3 LTS

### PR DESCRIPTION
**Pull request by ojs87**
#### Issue
When creating a meeting in the meetings module, the invite notification emails are only going to the first invited user/contact/lead.

#### Expected Behavior
All invitees should receive a meeting invite email

#### Actual Behavior
1 invitee is emailed.

#### Possible Fix
Check against an array of user ids rather than a boolean when preventing duplicate emails caused by workflow hooks

#### Steps to Reproduce
1. Create a meeting in the meetings module
2. Invite more than 1 user
3. Hit Save and send invites
4. Check logs or mailcatcher if set up

#### Context
Need to make sure all meeting invitees receive an invitation email.
https://github.com/salesagility/SuiteCRM/issues/9358

#### Your Environment
* SuiteCRM Version used: 7.12.0
* Browser name and version: Firefox Version 94.0 (64-bit))
* Environment name and version: PHP 7.4
* Operating System and version: Ubuntu 20.04.3 LTS

### CODE REVIEW

**Review by jack7anderson7 — APPROVED** [review]

**Comment by tsmgeek** [comment]
Note that this is targeting 7.10 branch but issue ticket is 7.12.

File: data/SugarBean.php [hunk 1]
```diff
@@ -3266,7 +3266,7 @@ public function send_assignment_notifications($notify_user, $admin)
                     $GLOBALS['log']->fatal("Notifications: error sending e-mail (method: {$notify_mail->Mailer}), " .
                         "(error: {$notify_mail->ErrorInfo})");
                 } else {
-                    $this->sentAssignmentNotifications = true;
+                    $this->sentAssignmentNotifications[] = $notify_user->id;
```
Comment (clemente-raposo) [inline data/SugarBean.php:3269]: Hi  @ojs87,

Thank you for the pull request.

`MeetingTest.php` and  `CasetTest.php` are expecting this to a boolean. Could you also update the tests please?

Another thing, I think it would be good to declare `sentAssignmentNotifications` as an `array` at the top of the `SugarBean` class. This avoids a notice, that we are probably getting at the moment.

Comment (ojs87) [reply data/SugarBean.php:3269]: Hi Clemente, 
Thanks for the feedback, I'll make the suggested changes.

**Review by jack7anderson7 — DISMISSED** [review]

**Review by clemente-raposo — APPROVED** [review]
changes look ok

**Review by jack7anderson7 — APPROVED** [review]

**Review by mattlorimer — APPROVED** [review]
