### PR TITLE
Fix #9783 - Compose view quick search for email templates

### LINKED ISSUE #9783: Compose Email view doesn't quick search Email Template field
#### Issue
The Email Template field in the emails module Compose View doesn't trigger quick search when typing in the field. 

#### Expected Behavior
The ideal situation would be for quick search to be enabled and to activate the confirmation dialogue box when a template is chosen.

#### Actual Behavior
There's no quick search on the Email Template field.

#### Possible Fix
Add 'ComposeView' to TemplateHandler.php condition that builds the quick search and required fields javascript

#### Steps to Reproduce
1. Go to Emails module
2. Click on Compose
3. In the Email Template Field type "C"
4. A list of email templates beginning with C should be displayed
5. No email template options are displayed

#### Context

The quick search feature is handy to have on this relate field so that opening the pop-up isn't required

#### Your Environment

* SuiteCRM Version used: 7.12.7
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 105 64-bit
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04.5 LTS

### PR DESCRIPTION
**Pull request by ojs87**
## Description
See https://github.com/salesagility/SuiteCRM/issues/9783

Email templates doesn't activate quick search when typing in the field in the Emails module compose view

## Motivation and Context
Quick search feature is handy to have on this relate field so that opening the pop-up isn't required

## How To Test This
1. Go to the Emails module
2. Click on Compose
3. In the Email Template Field type "C"
4. A list of email templates beginning with C should be displayed
5. No email template options are displayed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Emails/include/ComposeView/EmailsComposeView.js [hunk 1]
```diff
@@ -1366,6 +1366,41 @@
     });
   };
 
+  $.fn.EmailsComposeView.onTemplateChange = function (args) {
```
Comment (clemente-raposo) [inline modules/Emails/include/ComposeView/EmailsComposeView.js:1369]: Hi @ojs87 thank you for your PR. Is there a chance that `onTemplateChange` is called when `onTemplateSelect` is also called?

Comment (ojs87) [reply modules/Emails/include/ComposeView/EmailsComposeView.js:1369]: Hi @clemente-raposo I don't believe this is the case, I tested and it seems that since the field is not being typed in/manipulated by the user, when selecting a template from the popup, the onchange event doesn't occur.

Comment (clemente-raposo) [reply modules/Emails/include/ComposeView/EmailsComposeView.js:1369]: Thank you @ojs87

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — CHANGES_REQUESTED** [review]
Hey @ojs87 

It looks as though the functionality works well on the Standard Emails->Compose view.

However, If you are on the Compose Email Popup, (ie: Accounts->Activities->Compose Email). selecting an Email Template via the Auto-Complete causes the template to not be applied.

Selecting via standard select Popup:
image
image


Selecting via Auto-complete:
image

I believe this may be worth resolving, so as to keep functionality consistent across the CRM.

What are your thoughts?

Thanks!

**Comment by ojs87** [comment]
thanks for testing @johnM2401 

I did test this and it worked for me, although there are more issues with the popup than the standard compose, for example closing and reopening the popup seems to break the auto complete. 

Are you sure it isn't working on the popup compose?

**Review by johnM2401 — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
Hey @ojs87 

Apologies, I've pulled this PR down again and it appears to work as expected on both Compose Popup & Email->Compose Editview

Perhaps something was cached last time around?

Either way, I have Checked on both Firefox & Chromium, LGTM!

**Comment by ojs87** [comment]
> Hey @ojs87
> 
> Apologies, I've pulled this PR down again and it appears to work as expected on both Compose Popup & Email->Compose Editview
> 
> Perhaps something was cached last time around?
> 
> Either way, I have Checked on both Firefox & Chromium, LGTM!

Not to worry, I had a feeling you had tested this before and came up with the same issue and I fixed it then, so I just double checked it was still in the PR. Must have been a js caching issue.
Thanks!
