### PR TITLE
Fixed #3420 - Regular user does not reach email address field in Reports module

### LINKED ISSUE #3420: Regular user does not reach email address field in Reports module
#### Issue

I'm trying to create a report that will display the account and or contact's e-mail address among other information like opt out field. When creating the report the field for e-mail address is not available. 
I can create my reports and reach email field when i as an administrator user. When i as a regular user, i could not reach this field.
#### Expected Behavior

It should be available for permitted users.
#### Steps to Reproduce

1. Open Reports module and create new report.
2. Select contacts module
3.  Choose Email Address : Email Address and Email Address
4. Fields (Email Address) box is empty
screenshot_1

#### Your Environment

* SuiteCRM Version used: 7.8.3
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome latest
* Environment name and version (e.g. MySQL, PHP 7): PHP 7
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04
* Theme: Suite7

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When attempting to select "Email Addresses" from the reports module tree a non-admin use is shown blank fields. This change gives non-admin users access to the email address category when using AOR_Reports in the ACLController.

issue-4067

## Motivation and Context

Issue reference: #4067 
Issue reference: #3420

## How To Test This

1. As a non-admin user create a report on Accounts
2. Check that "Email addresses" is populated with the email address fields.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/ACL/ACLController.php [hunk 1]
```diff
@@ -34,226 +34,270 @@
...
-		echo '<script>function set_focus(){}</script><p class="error">' . translate('LBL_NO_ACCESS', 'ACL') . '</p>';
-		if($redirect_home)echo translate('LBL_REDIRECT_TO_HOME', 'ACL') . ' <span id="seconds_left">3</span> ' . translate('LBL_SECONDS', 'ACL') . '<script> function redirect_countdown(left){document.getElementById("seconds_left").innerHTML = left; if(left == 0){document.location.href = "index.php";}else{left--; setTimeout("redirect_countdown("+ left+")", 1000)}};setTimeout("redirect_countdown(3)", 1000)</script>';
-	}
-
-}
 
+class ACLController
+{
+    /* BEGIN - SECURITY GROUPS - added $in_group */
+    static function checkAccess($category, $action, $is_owner = false, $type = 'module', $in_group = false)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 2]
```diff
@@ -34,226 +34,270 @@
...
+                    $in_group
+                );
+        }
+
+        return ACLAction::userHasAccess($current_user->id, $category, $action, $type, $is_owner, $in_group);
+    }
+
+    /* END - SECURITY GROUPS */
+
+    static function requireOwner($category, $value, $type = 'module')
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 3]
```diff
@@ -34,226 +34,270 @@
...
+        global $current_user;
+        if (is_admin($current_user)) {
+            return false;
+        }
+
+        return ACLAction::userNeedsOwnership($current_user->id, $category, $value, $type);
+    }
+
+    /* BEGIN - SECURITY GROUPS */
+    static function requireSecurityGroup($category, $value, $type = 'module')
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 4]
```diff
@@ -34,226 +34,270 @@
...
+        if (is_admin($current_user)) {
+            return false;
+        }
+
+        return ACLAction::userNeedsSecurityGroup($current_user->id, $category, $value, $type);
+    }
+
+    /* END - SECURITY GROUPS */
+
+    static function filterModuleList(&$moduleList, $by_value = true)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 5]
```diff
@@ -34,226 +34,270 @@
...
+
+    }
+
+    /**
+     * Check to see if the module is available for this user.
+     *
+     * @param String $module_name
+     * @return true if they are allowed.  false otherwise.
+     */
+    static function checkModuleAllowed($module_name, $actions)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 6]
```diff
@@ -34,226 +34,270 @@
...
+        if (!empty($actions[$module_name]['module']['access']['aclaccess']) &&
+            ACL_ALLOW_ENABLED == $actions[$module_name]['module']['access']['aclaccess']
+        ) {
+            return true;
+        }
+
+        return false;
+    }
+
+    static function disabledModuleList($moduleList, $by_value = true, $view = 'list')
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 7]
```diff
@@ -34,226 +34,270 @@
...
+            $disabled['ProductTemplates'] = 'ProductTemplates';
+        }
+
+
+        return $disabled;
+
+    }
+
+
+    function addJavascript($category, $form_name = '', $is_owner = false)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 8]
```diff
@@ -34,226 +34,270 @@
...
+    {
+        $jscontroller = new ACLJSController($category, $form_name, $is_owner);
+        echo $jscontroller->getJavascript();
+    }
+
+    static function moduleSupportsACL($module)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?

File: modules/ACL/ACLController.php [hunk 9]
```diff
@@ -34,226 +34,270 @@
...
+            } else {
+                $checkModules[$module] = $mod->bean_implements('ACL');
+            }
+        }
+
+        return $checkModules[$module];
+
+    }
+
+    static function displayNoAccess($redirect_home = false)
```
Comment (daniel-samson) [inline modules/ACL/ACLController.php]: missing public/protected/private?
