### PR TITLE
Fix #2464 - logo upload

### LINKED ISSUE #2464: Logo upload function is not working
#### Issue

The logo upload function is not working. A message with the type of supported images is shown even though a supported image is uploaded.
#### Expected Behavior

The logo image should be uploaded.
#### Actual Behavior

A message indicating supported image types is shown.
#### Possible Fix

The variable '$upload->temp_file_location' includes a path with the extension 'tmp' in the file 'modules/Configurator/UploadFileCheck.php'
#### Steps to Reproduce
1. Login
2. Go to the administration section
3. Click on system settings
4. Attempt to upload a image with a supported extension

image
#### Context

I was trying to change the logo that is shown on the login screen of SuiteCRM.
#### Your Environment

SuiteCRM 7.7.4 using Microsoft SQL Server and PHP 7 on IIS.

### PR DESCRIPTION
**Pull request by pgorod**
## Description
Please see Issue #2464

Another user recently confirmed in the forums that this works
https://suitecrm.com/suitecrm/forum/suite-themes/27994-unable-to-replace-logo-with-png-extension#92257

### CODE REVIEW

**Comment by Mac-Rae** [comment]
Assessed :+1:

File: include/utils.php [hunk 1]
```diff
@@ -5201,7 +5201,7 @@ function verify_image_file($path, $jpeg = false)
  */
 function verify_uploaded_image($path, $jpeg_only = false)
 {
-    $supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg');
+    $supportedExtensions = array('jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg', 'tmp' => 'tmp');
```
Comment (Dillon-Brown) [inline include/utils.php]: Seems fine but I wonder if there are security implications we'd need to consider here if we start allowing ```tmp``` files to be uploaded.

Comment (pgorod) [reply include/utils.php]: I've wondered about that but I get the feeling it's not going to be a problem. 
This extension is only `tmp` because we name the logo file like that (we could change _that_ of course).
About people uploading _other_ files with `tmp` extension, I don't think that makes much of a difference anyway. `tmp` files are _never_ executable, I believe.

But we really should work for a solution here, it's ridiculous how difficult it's been to upload a Logo into SuiteCRM, for so long. It's the first thing most people do after installing...

Comment (Dillon-Brown) [reply include/utils.php]: Agreed, although looking at how we verify uploaded images I think we should probably improve it, doesn't seem like it actually validates much.... This should be fine for a quick fix to get logo uploads working though.
