### PR TITLE
Fixed #6504 - Fix and implement proper bounce email handling

### LINKED ISSUE #5980: Bounced Emails are not processed properly in SuiteCRM 7.10.5
When the Email Campaign is executed, it does not process the bounced email in appropriate manner.  

#### Issue
The campaign sent/attempted 534-emails.  There were 66-emails which were returned with the message: "A message that you sent could not be delivered to one or more of its   recipients. This is a permanent error."  However, 2-issues were presented:
1.  All these 66-emails were returned to the email ID which was, e.g. info@yourdomain.com, configured as 'From' & 'Return To' email address.  Note:  The emails were sent via the outbound system account, which was same as info@yourdomain.com.  I believe that these emails should have returned to the email id, 'bounces@yourdomain.com' which was pre-configured as ID meant for bounced emails.
2.  None of these 66-emails which returned were lodged as Bounced Emails in the STATUS REPORT of the campaign.
image

#### Expected Behavior
These 66-emails should have been considered/recorded as bounced emails appropriately, based upon the error code these emails generated.  For examples:
452  1-Email
550  9-Emails
554  7-Emails
550 5.1.1 1-Email
550 5.1.10  1-Email
550 5.7.1  4-Emails
550-5.1.1  7-Emails
550-5.2.1  25-Emails
550-5.2.2  4-Emails
(No code)  7-Emails

The summary compiled of all emails which returned is attached herewith:
[TEMP1.xlsx](https://github.com/salesagility/SuiteCRM/files/2064866/TEMP1.xlsx)

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* SuiteCRM Version used:  7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):  Latest
* Environment name and version (e.g. MySQL, PHP 7):  PHP 7.1
* Operating System and version (e.g Ubuntu 16.04):

### LINKED ISSUE #6504: Multiple bounce handling problems
#### Issue

* Imported bounce emails are not always linked with the campaign logs
* Imported bounce emails are not detected as hard bounces
* Marking emails as invalid based on hard bounces doesn't work

Related issues: #5980, #5898, #1578

#### Expected Behavior

When SuiteCRM fetches a bounce email over IMAP it should show up in the
campaign stats and on hard bounces it should mark the email as invalid.

#### Actual Behavior

Even though there is a proper bounce email imported it doesn't show up in the
campaign stats and on hard bounces the email address isn't marked as invalid.

#### Possible Fix

I've opened the PR #6505 to fix this

#### Steps to Reproduce

1. Set up bounce handling in SuiteCRM
2. Create campaign and add a contact with a non-existing email address
3. Send a campaign email
4. Watch the bounce inbox and wait until the email is read
5. Check the the campaign stats

#### Your Environment

* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 63
* Environment name and version (e.g. MySQL, PHP 7): PHP7.2
* Operating System and version (e.g Ubuntu 16.04): CentOS 7

### PR DESCRIPTION
**Pull request by lazka**
## Description

Bounce handling is currently broken for multiple reasons:

(1) The imported bounce email is saved in the notes description field which is
marked as text and strips away all HTML on save(). This removes/mangles the
link containing the tracking ID so the attachment can't be linked to the
campaign log later on.

(2) SMTP servers usually return the original email as an attachment on a
bounce and include an addition attachment containing the delivery status (RFC
3464). Since this attachment wasn't saved, hard bounces weren't detected.

(3) In case the tracking ID makes it through and the email is considered a
hard bounce then marking the email as invalid failed because
markEmailAddressInvalid() was called with an email object but expected a
string.

To fix all these:

For (1) we don't save the attachment in the description and read it from the
saved attachment file instead. This makes sure we get the original content and
can extract the tracking ID.

For (2) we also save the delivery-status attachments in addition to the email
copy and also evaluate it in the bounce handling code. This allows us to
confidently classify hard bounces by parsing the status and diagnostic fields
in the delivery status attachment.

For (3) fix markEmailAddressInvalid() to take a bounce entry and figure out
the email address from there and mark it as invalid.

## Motivation and Context

To fix #6504

This likely also fixes #5980, #5898 and #1578

## How To Test This

See #6504

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribut

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @lazka 

just so you don't have only bots 🤖 talking to you, I want to personally thank you for your recent contributions, very valuable.

Thanks!

**Comment by lazka** [comment]
Thanks 😊

If there is anything I should do differently or improve just let me know!

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 1]
```diff
@@ -101,20 +107,58 @@ function createBouncedCampaignLogEntry($row, $email, $email_description)
 }
 
 /**
- * Given an email address, mark it as invalid.
+ * Given the email description returns if the email should be marked invalid.
  *
  * @param $email_address
+ * @return bool
  */
-function markEmailAddressInvalid($email_address)
```
Comment (gymad) [inline modules/Campaigns/ProcessBouncedEmails.php]: I understand if you change the function name it makes more logical and readable the code itself but this change could brakes the backward compatbility to any customization which already exists and possible usage of current exists functions.

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 2]
```diff
@@ -101,20 +107,58 @@ function createBouncedCampaignLogEntry($row, $email, $email_description)
...
+            return TRUE;
     }
+
+    return FALSE;
+}
+
+/**
+ * Given an bounce entry, mark the related email address as invalid.
+ *
+ * @param $bounce
```
Comment (gymad) [inline modules/Campaigns/ProcessBouncedEmails.php]: Please update the phpdoc with parameter type.

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 3]
```diff
@@ -101,20 +107,58 @@ function createBouncedCampaignLogEntry($row, $email, $email_description)
...
+ */
+function markBounceEmailAddressInvalid($bounce)
```
Comment (gymad) [inline modules/Campaigns/ProcessBouncedEmails.php]: Please add class name as typehinting before parameter.

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 4]
```diff
@@ -101,20 +107,58 @@ function createBouncedCampaignLogEntry($row, $email, $email_description)
...
+{
     $sea = new SugarEmailAddress();
-    $rs = $sea->retrieve_by_string_fields(array('email_address_caps' => trim(strtoupper($email_address))));
-    if ($rs != null) {
+    $email_address = $sea->getPrimaryAddress(false, $bounce->target_id, $bounce->target_type);
+    if (empty($email_address))
+        return;
+
+    $GLOBALS['log']->info("Marking email address as invalid: ". $email_address);
```
Comment (gymad) [inline modules/Campaigns/ProcessBouncedEmails.php]: You could using LoggerManager::getLogger() method instead superglobals.

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 5]
```diff
@@ -166,15 +210,12 @@ function campaign_process_bounced_emails(&$email, &$email_header)
...
     $email_description = $email->raw_source;
 
-    //if raw_source is empty, try using the description instead
-    if (empty($email_description)) {
-        $email_description = $email->description;
-    }
-
     $email_description .= retrieveErrorReportAttachment($email);
 
+    // TODO: Delete attachments after this?
```
Comment (gymad) [inline modules/Campaigns/ProcessBouncedEmails.php]: Do not leave TODO comment in the code. It's implicate you miss something?

File: modules/Notes/Note.php [hunk 6]
```diff
@@ -205,6 +205,24 @@ public function get_summary_text()
         return "$this->name";
     }
 
+    /**
+     * Returns the content or an empty string if there is no attachment or it
+     * couldn't be located.
+     *
+     * @return string
+     */
+    public function getAttachmentContent()
```
Comment (gymad) [inline modules/Notes/Note.php]: This function returns an empty string in cases:
- file not exists
- file_get_contents() failure
- file is empty
I think it's confusing, the caller does not know why is the empty string passed if any problem occured.

File: modules/Notes/Note.php [hunk 7]
```diff
@@ -205,6 +205,24 @@ public function get_summary_text()
...
+    {
+        $path = "upload://{$this->id}";
+        if (!file_exists($path))
+            return '';
+
+        $result = file_get_contents($path);
+        if ($result === FALSE)
```
Comment (gymad) [inline modules/Notes/Note.php]: please use PSR standard const names.
see more: https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull

File: modules/Campaigns/ProcessBouncedEmails.php [hunk 8]
```diff
@@ -56,10 +56,17 @@
 function retrieveErrorReportAttachment($email)
```
[the remark this answers is not in the document]
Comment (lazka) [reply modules/Campaigns/ProcessBouncedEmails.php]: Ah, good catch, I've added a type hint, added sql quoting and a small unit test.

File: modules/Campaigns/ProcessBouncedEmails.php (hunk 1 above)
Comment (lazka) [reply modules/Campaigns/ProcessBouncedEmails.php]: ok, I've left the old function as is an made the new one call the old one.

File: modules/Campaigns/ProcessBouncedEmails.php (hunk 5 above)
Comment (lazka) [reply modules/Campaigns/ProcessBouncedEmails.php]: It's just that I searched for related bug reports before I started working on this and this would be a place for fixing it, but I haven't looked into it. But that's another issue. I've removed the TODO

File: modules/Notes/Note.php (hunk 6 above)
Comment (lazka) [reply modules/Notes/Note.php]: I've changed it to return false or a string now.

File: modules/Notes/Note.php (hunk 7 above)
Comment (lazka) [reply modules/Notes/Note.php]: OK, thanks

**Comment by lazka** [comment]
I think I've addressed all issues raised so far (minus the open conversation)

File: modules/Notes/Note.php [hunk 9]
```diff
@@ -205,6 +205,21 @@ public function get_summary_text()
...
+    /**
+     * Returns the content as string or false if there is no attachment or it
+     * couldn't be located.
+     *
+     * @return bool|string
+     */
+    public function getAttachmentContent()
+    {
+        $path = "upload://{$this->id}";
+        if (!file_exists($path))
```
Comment (code-ph0y) [inline modules/Notes/Note.php]: Please use { } with if statements.

For-example: 

```
if (!file_exists($path)) {
    return false;
}
```

Comment (lazka) [reply modules/Notes/Note.php]: thanks, done (also in other places)

**Comment by MoritzKosubek** [comment]
got a question: How often do you run your Schedluer for this? every 15 minutes or less?

**Comment by cameronblaikie** [comment]
Assessed :+1:

**Comment by mayerelyashiv** [comment]
Dear @lazka, thank you very much;
anyway on a 7.10.27 i found that sending Email Campaigns to a not existing email address produces a "Suppressed by Domain" activity instead of "Invalid Email.

I tried to copy your 5 files hotfix but nohing changed.

Have you any hint about it, please?

**Comment by lazka** [comment]
As far as I remember this only handles the case when you get back a bounce email in your bounce imap inbox. Do you see a bounce email for that "message" there? (using an offline email client maybe)

**Comment by lazka** [comment]
This PR only fixed the parsing of those emails fetched from the inbox. If they don't end up there then something else is broken.

**Comment by mayerelyashiv** [comment]
Hi @lazka; i did a lot of tests (on 7.10.27 instances)
Even if i'm receiving a lot of bounce emails in my bounce imap inbox (checking with Gmail and Thunderbird) SuiteCRM is not marking any of those email addresses as invalid, nor it's adding them to the proper Bounced Messages response list.

**Comment by aimran50** [comment]
Email communication via a CRM and proper account management(which includes marking invalid email addresses) is a critical function. Looks like this has been broken for a long time. Is there any plan to fix this problem?

**Comment by pgorod** [comment]
> anyway on a 7.10.27 i found that sending Email Campaigns to a not existing email address produces a "Suppressed by Domain" activity instead of "Invalid Email".

☝️ is this still what we're talking about, or something different?

I'd start by having a look at 
https://github.com/salesagility/SuiteCRM/blob/master/modules/EmailMan/EmailMan.php

Specifically, every call to **`set_as_sent`**. find out which one corresponds to the handling situation you're not happy with.
