### PR TITLE
Fixed #3279 - PHP Warning logged for Calendar Dashlet

### LINKED ISSUE #3279: PHP Warning logged for Calendar Dashlet / low priority but annoying
#### Issue
When a Calendar Dashlet is used a PHP Warning is logged every time the Dashlet reloads. 

PHP Warning:  Creating default object from empty value in /www/htdocs/anholt/scrm/modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php on line 66

#### Expected Behavior
No spamming in logfile

#### Actual Behavior
hundreds of useless lines over a day in the logfile

#### Steps to Reproduce
1. enable "My Calendar" Dashlet (not sure of the term since I use the german translation "Meine Kalender") 
2. reload front page

#### Your Environment

* SuiteCRM Version used: Version 7.8.2 - Sugar Version 6.5.24 (Erstellen 509)
* Browser name and version: Chrome Version 56.0.2924.87 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): PHP 5.5.38, MySQL 5.6.33

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When a Calendar Dashlet is used a PHP Warning is logged every time the Dashlet reloads.

PHP Warning: Creating default object from empty value in /Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php on line 66

## Motivation and Context

Issue reference: #3279

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php [hunk 1]
```diff
@@ -34,97 +34,135 @@
...
 require_once('include/Dashlets/Dashlet.php');
 
+class CalendarDashlet extends Dashlet
+{
+    public $view = 'week';
+
+    /**
+     * @see Dashlet::__construct()
+     */
+    public function __construct($id, $def)
```
Comment (daniel-samson) [inline modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php]: Please update PHP so with the params. Remember to also put their respective types.

File: modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php [hunk 2]
```diff
@@ -1,11 +1,11 @@
...
+/**
+ *
  * SugarCRM Community Edition is a customer relationship management program developed by
  * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
-
- * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
- * Copyright (C) 2011 - 2014 Salesagility Ltd.
+ *
+ * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
+ * Copyright (C) 2011 - 2017 SalesAgility Ltd.
```
Comment (daniel-samson) [inline modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php]: Old License?

File: modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php [hunk 3]
```diff
@@ -34,97 +34,135 @@
...
+        return parent::displayOptions() .
+            $ss->fetch('modules/Calendar/Dashlets/CalendarDashlet/CalendarDashletOptions.tpl');
+    }
 
-    function saveOptions($req) {
-        global $sugar_config, $timedate, $current_user, $theme;
+    /**
+     * @see Dashlet::saveOptions()
+     */
+    public function saveOptions($req)
```
Comment (daniel-samson) [inline modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php]: There seems to be a mixture of $_REQUEST and $req in this function. Are these the same?

The PHP Doc needs to be updated to represent this param. Also if the $req is the same as $_REQUEST, we should  use the param instead of the $_REQUEST.
