### PR TITLE
Fix #5390 - Redundant message when duplicating a survey

### LINKED ISSUE #5390: Redundant message when duplicating a survey
#### Issue
The message 'Survey questions with responses cannot be edited' should not be displayed when duplicating a survey.

#### Steps to Reproduce

1. Open any survey **with some responses**
2. Select Duplicate item from the Action menu
3. The message 'Survey questions with responses cannot be edited' is displayed in survey  without any responses.

default

#### Your Environment

* SuiteCRM Version used: Hotfix branch

### PR DESCRIPTION
**Pull request by serhiisamko091184**
Fixes issue #5390

## Description

https://github.com/salesagility/SuiteCRM/issues/5390

## Motivation and Context

We check through global request weather data comes from duplication button or not. It helps to show message where it's necessary and avoid where it is not.  

## How To Test This

All the detail are given in the issue description. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Surveys/Lines/Lines.php [hunk 1]
```diff
@@ -27,7 +27,7 @@ function ($a, $b) {
     );
     $smarty->assign('questions', $questions);
     $smarty->assign('message', '');
-    if ($view == 'EditView') {
+    if ($view == 'EditView' && $_REQUEST['isDuplicate'] === false) {
```
Comment (clemente-raposo) [inline modules/Surveys/Lines/Lines.php:30]: Hi @serhiisamko091184, we need  to check if `$_REQUEST['isDuplicate']` is set, otherwise we can get warnings/notices. Something like:

```
$isDuplicate = $_REQUEST['isDuplicate'] ?? false
if ($view == 'EditView' && isDuplicate === false) {
```

Comment (serhiisamko091184) [reply modules/Surveys/Lines/Lines.php]: Thanks for feedback @clemente-raposo ,
I did requested changes. 
Thanks a lot!

Regards,
Serhii

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
