### PR TITLE
Fix #8980 - Check beanFiles for class path

### LINKED ISSUE #8980: CustomDocuments Object Causes download.php to fail
#### Issue

When user extends the Document.php class, and downloads fail with the message: 

`Error. This type is not valid.`

#### Expected Behavior

downloads.php should reference the beanFiles values for the path, instead of creating path from scratch to the wrong location.
#### Actual Behavior

User is presented with error page with only the following content: 
`Error. This type is not valid.`
#### Possible Fix

Will provide a fix: basically patch:
download.php with : `if (!file_exists($beanFiles[$bean_name])) {`
#### Steps to Reproduce

1. Extend Documents by putting new file in custom/modules/Documents/Document.php:
```
<?php
if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}
require_once 'modules/Documents/Document.php';


class CustomDocument extends Document
{
}
```
2. Add mapping file: to custom/Extension/application/Ext/Include/customDocumentMapping.php
`<?php
List['Documents'] = 'Document';
$beanList['Documents'] = 'CustomDocument';
$beanFiles['CustomDocument'] = 'custom/modules/Documents/Document.php';`
3. Run repair from admin console
4. Find a document you would like to download All->Documents (Formal)
5. Click on one of the file names in the list view

#### Context

Anyone customizing the Documents (and maybe Notes) will encounter this.  
Medium
#### Your Environment

* SuiteCRM Version used: 7.11.15
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome
* Environment name and version (e.g. MySQL, PHP 7): php 7, mysql
* Operating System and version (e.g Ubuntu 16.04): docker.io/bitnami/suitecrm:7-debian-10

### PR DESCRIPTION
**Pull request by sweettbug3**
BeanFiles global provides the path to the overwritten class for customizations.

## Description
See #8980 

## Motivation and Context

Cannot download files if extending Documents Bean.
## How To Test This

See how to reproduce in #8980 
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x ] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [ x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @sweettbug3 ,
Thanks a lot for updating your contribution. 

Regards, 
Serhii

File: download.php [hunk 1]
```diff
@@ -75,7 +75,8 @@
         if ($bean_name == 'aCase') {
             $bean_name = 'Case';
         }
-        if (!file_exists('modules/' . $module . '/' . $bean_name . '.php')) {
+        global $beanFiles;
+        if (!file_exists($beanFiles[$bean_name])){
```
Comment (clemente-raposo) [inline download.php:79]: Hi @sweettbug3,

thank you for your PR.

Could you also add a validation to check if the `$bean_name` within `$beanFiles`.

Maybe something like

```
global $beanFiles;
$beanFileName = $beanFiles[$bean_name] ?? '';
if ($beanFileName === '' || !file_exists($beanFileName)){
```

**Comment by sweettbug3** [comment]
I would like to help with this, but I have way too much on my plate to fix this currently

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
