### PR TITLE
FIXED #7979 - Reports Total table squished

### LINKED ISSUE #7979: Reports Total table squished
#### Issue

The Report Total field became much smaller at some point and looks weird compared to the main Reports table (I don't think this is the same as #7964?).

See also https://suitecrm.com/suitecrm/forum/feedback/24368-problem-in-the-report-module-with-columns-width-in-the-total-row-of-a-report-table

#### Expected Behavior
The report's Total table would span the full width of its container.

#### Actual Behavior
It's squished into a very small width, only as long as the column title needs.

Screen Shot 2019-10-04 at 3 13 01 PM

This was posted in the forum thread as an example:

image

#### Possible Fix
It seems like we can mostly fix it by adding these classes and width 100% to the table (right now it's literally just a `<table>` tag with no attributes):

```html
<table width="100%" class="list view table-responsive aor_reports">
  <!-- table stuff -->
</table>
```

This is what it looks like with that change:

Screen Shot 2019-10-04 at 3 18 26 PM

It has extra columns (same number as the report?) for some reason, which is why the header text is weirdly aligned.

#### Steps to Reproduce
1. Create a Report in the AOR_Reports module, with a 'total' field.
2. View the report.
3. See that the total field's table is much smaller than the main table.

#### Context
It looks ugly :)

#### Your Environment
* SuiteCRM Version used: 7.10.19
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 79, Firefox 69
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by cameronblaikie**
The Report Total field became much smaller at some point and looks weird compared to the main Reports table
## Motivation and Context

https://github.com/salesagility/SuiteCRM/issues/7979
## How To Test This

  1.  Create a Report in the AOR_Reports module, with a 'total' field.
  2.  View the report.
  3.  See that the total field's table is much smaller than the main table.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/AOR_Reports/AOR_Report.php [hunk 1]
```diff
@@ -955,7 +955,7 @@ public function getTotalHTML($fields, $totals)
         $currency->retrieve($GLOBALS['current_user']->getPreference('currency'));
 
         $showTotal = false;
-        $html = '<table>';
+        $html = '<table width="100%" class="list view table-responsive aor_reports">';
```
Comment (Dillon-Brown) [inline modules/AOR_Reports/AOR_Report.php]: Not necessarily required to merge but it would be better to separate this out into a template and use smarty.

**Comment by connorshea** [comment]
You'll need to update `tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php` to match the new HTML output.

File: tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php [hunk 2]
```diff
@@ -244,12 +244,13 @@ public function testbuild_report_html()
...
     }
 
-    public function testgetTotalHTML()
+    public function testGetTotalHTML()
     {
         //execute the method with required data preset and verify it returns expected result
         $fields = array('label' => array('display' => 1, 'total' => 'SUM', 'label' => 'total'));
         $totals = array('label' => array(10, 20, 30));
-        $expected = "<table><thead class='fc-head'><tr><th>total Sum</th></tr></thead><tbody><tr class='oddListRowS1'><td>60</td></tr></tbody></table>";
+        $expected = "<table width='100%' class='list view table-responsive aor_reports'><thead class='fc-head'><tr><th>total Sum</th></tr></thead><tbody><tr class='oddListRowS1'><td>60</td></tr></tbody></table>";
```
Comment (connorshea) [inline tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php]: It looks like the tests are failing because they expect these to be double quotes rather than single quotes?

**Comment by connorshea** [comment]
It'll need to be changed again because of #7965 >.>

This test is pretty crap, it should really be changed to just check for the text, not the exact HTML.

The actual expected output should be this, I think?:

```
<table width='100%' class='list view table-responsive aor_reports'><thead class='fc-head'><tr><th>total Sum</th></tr></thead><tbody><tr class='oddListRowS1'><td>
<span class="sugar_field" id="duration_hours">
60
</span></td></tr></tbody></table>
```

**Comment by Mac-Rae** [comment]
Assessed :+1:
