### PR TITLE
Fix #9873 - Plesk php.ini disable_functions = opcache_get_status

### LINKED ISSUE #9873: Attempted to call function “opcache_get_status” / 500 error (Plesk config)
Running php 8.0 with the following php.ini setting

`disable_functions = opcache_get_status`

leads to 500 server errors and failure to install SuiteCRM

#### Issue

The above configuration is typical for installations with Plesk, in which the function opcache_get_status is disabled by default.
It can be provoked by trying to edit a module label.

See also
https://community.suitecrm.com/t/moved-suitecrm-to-new-vps-with-php-8-pukes-all-over-it-version-7-12-8
https://community.suitecrm.com/t/cant-install-suitecrm-8-1-3-attempted-to-call-function-opcache-get-status-from-the-global-namespace
https://community.suitecrm.com/t/suitecrm-7-12-x-7-13-x-php-8-0-x

#### Steps to Reproduce

- edit php.ini and set
  `disable_functions = opcache_get_status`
- open studio
- open the module "accounts"
- click "Labels"
- modify the value for first label "LBL_ANNUAL_REVENUE"
- click "Save & Deploy"

#### Expected Behavior

The message: "The operation completed successfully"

#### Actual Behavior

The message: "An error has occured" appears
The apache/nginx error file shows:
`PHP Fatal error:  Uncaught Error: Call to undefined function opcache_get_status() in /var/www/html/suite7130/include/SugarCache/SugarCache.php:168`

#### Possible Fix
See attached PR

#### Context

Only systems running Plesk are affected

#### Your Environment
* SuiteCRM Version used: 7.13.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): irrelevant
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.0
* Operating System and version (e.g Ubuntu 16.04): irrelevant

### PR DESCRIPTION
**Pull request by JanSiero**
Fixes compatibility with PHP 8.0 for Plesk users

## Description
PHP configurations which have the following configured in php.ini
`disable_functions = opcache_get_status`

will not be able to install or use SuiteCRM from 8.0 as disabled functions now trigger a fatal error
https://php.watch/versions/8.0/disable_functions-redeclare

The code for SugarCache uses a check which uses the function opcache_get_status to retrieve detailed information on the current opcache configuration

## Motivation and Context
Plesk users have the above php.ini configuration as default are are not able to install SuiteCRM with the default configuration with php 8.0

This change provides a graceful degradation for installations which have opcache_get_status disabled by checking the opcache configuration using the more archaic function "ini_get" to retrieve its status.

Besides an opcache_invalidate call was removed from the method "write_override_label_to_file" as this is already taken care of in "sugar_file_put_contents"

## How To Test This
See https://github.com/salesagility/SuiteCRM/issues/9873

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by jack7anderson7** [comment]
Hi @JanSiero,

Sorry to keep correcting you, but we see you have `Fixed` instead of `Fix` could you please update this.

Thanks,
Jack

**Comment by JanSiero** [comment]
Hi @jack7anderson7 , I hope this helps, best regards!

File: include/SugarCache/SugarCache.php [hunk 1]
```diff
@@ -143,8 +143,10 @@ public static function cleanOpcodes($full_reset = false)
         // Zend OPcache
         if (
             extension_loaded('Zend OPcache') &&
+            ((function_exists('opcache_get_status') &&
             ($opcache_status = opcache_get_status(false)) !== false &&
-            $opcache_status['opcache_enabled'] && $full_reset
+            $opcache_status['opcache_enabled'] ) || ini_get('opcache.enable') ) &&
+            $full_reset
```
Comment (clemente-raposo) [inline include/SugarCache/SugarCache.php:149]: Hi @JanSiero,

Thank you for your PR.

This condition is getting hard to read, could we do something like the following, please?

```php
$opcacheLoaded = extension_loaded('Zend OPcache');
$opcache_status_enabled = false;

if(function_exists('opcache_get_status')) {
    $opcache_status = opcache_get_status(false);
    $opcache_status_enabled = $opcache_status !== false && ($opcache_status['opcache_enabled'] ?? false);
}

$ini_opcache_enabled = ini_get('opcache.enable');

if (
    opcacheLoaded &&
    (opcache_status_enabled || $ini_opcache_enabled) &&
    $full_reset
) {
    if (!opcache_reset()) {
        LoggerManager::getLogger()->error("OPCache - could not reset");
    }
}
```

File: include/SugarCache/SugarCache.php [hunk 2]
```diff
@@ -165,8 +167,9 @@ public static function cleanFile($file)
         // Zend OPcache
         if (
             extension_loaded('Zend OPcache') &&
+            ((function_exists('opcache_get_status') &&
             ($opcache_status = opcache_get_status(false)) !== false &&
-            $opcache_status['opcache_enabled']
+            $opcache_status['opcache_enabled'] ) || ini_get('opcache.enable') )
```
Comment (clemente-raposo) [inline include/SugarCache/SugarCache.php:172]: Hi @JanSiero,

Same here, could we do something like the following please?

```php
$opcacheLoaded = extension_loaded('Zend OPcache');
$opcache_status_enabled = false;

if(function_exists('opcache_get_status')) {
    $opcache_status = opcache_get_status(false);
    $opcache_status_enabled = $opcache_status !== false && ($opcache_status['opcache_enabled'] ?? false);
}

$ini_opcache_enabled = ini_get('opcache.enable');


if (
    $opcacheLoaded &&
    ($opcache_status_enabled || $ini_opcache_enabled)
) {
    // three attempts incase concurrent opcache operations pose a lock
    for ($i = 3; $i && !opcache_invalidate($file, true); --$i) {

```

File: include/SugarCache/SugarCache.php (hunk 1 above)
Comment (JanSiero) [reply include/SugarCache/SugarCache.php:149]: Hi @clemente-raposo your code always retrieves the opcache status by ini_get, even when opcache_get_status was successful, although it was meant as a fallback.

To reduce the nr. of variables, and improve readability I'd propose this code. Can you assess this? Would you like me to adapt my pull request accordingly?

```php
        // Zend OPcache
        if (extension_loaded('Zend OPcache') {
            $opcache_status_enabled = false;
            
            if(function_exists('opcache_get_status')) {
                $opcache_status = opcache_get_status(false);
                $opcache_status_enabled = $opcache_status !== false && ($opcache_status['opcache_enabled'] ?? false);
            } else {
                $opcache_status_enabled = ini_get('opcache.enable');
            }
            
            if ($opcache_status_enabled && $full_reset) {
                if (!opcache_reset()) {
                    LoggerManager::getLogger()->error("OPCache - could not reset");
                }
            }
        }
```

File: include/SugarCache/SugarCache.php (hunk 2 above)
Comment (JanSiero) [reply include/SugarCache/SugarCache.php:172]: Idem

```php
Hi @clemente-raposo your code always retrieves the opcache status by ini_get, even when opcache_get_status was successful, although it was meant as a fallback.

To reduce the nr. of variables, and improve readability I'd propose this code. Can you assess this? Would you like me to adapt my pull request accordingly?

```php
        // Zend OPcache
        if (extension_loaded('Zend OPcache') {
            $opcache_status_enabled = false;
            
            if(function_exists('opcache_get_status')) {
                $opcache_status = opcache_get_status(false);
                $opcache_status_enabled = $opcache_status !== false && ($opcache_status['opcache_enabled'] ?? false);
            } else {
                $opcache_status_enabled = ini_get('opcache.enable');
            }
            
            if ($opcache_status_enabled) {
                // three attempts incase concurrent opcache operations pose a lock
                for ($i = 3; $i && !opcache_invalidate($file, true); --$i) {
                    sleep(0.2);
                }
            }
        }
```

File: include/SugarCache/SugarCache.php (hunk 1 above)
Comment (JanSiero) [reply include/SugarCache/SugarCache.php]: Hi @clemente-raposo I revised my code with a new push, I hope this helps.

**Review by clemente-raposo — APPROVED** [review]
LGTM

File: include/SugarCache/SugarCache.php (hunk 2 above)
Comment (clemente-raposo) [reply include/SugarCache/SugarCache.php]: @JanSiero thank you for the changes

File: include/SugarCache/SugarCache.php (hunk 1 above)
Comment (clemente-raposo) [reply include/SugarCache/SugarCache.php]: Hi @JanSiero thank you!

**Review by johnM2401 — APPROVED** [review]
LGTM
