### PR TITLE
Fixed #5197 - Importing Contacts saves every contacts email as the first email in the csv.

### LINKED ISSUE #5197: Importing Contacts saves every contacts email as the first email in the csv.
There was the same issue in a previous version, but users reported it to be fixed.  I confirmed it was not in version 7.9.9, then I upgraded to 7.9.12 and the issue appeared.

#### Issue

When importing contacts via the "Import Contacts" method each contact is saved with the first line's email address. The same email address is saved for more than the correct contact.

#### Expected Behavior

The correct email should be saved in each contact.

#### Actual Behavior
When importing a csv with the following contents.

Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3

When imported It adds the records as follows
First Name       Last Name    Email
First1                 Last1            test1@domain.com
First2                Last2            test1@domain.com
First3                Last3            test1@domain.com

#### Possible Fix
Unknown

#### Steps to Reproduce

1. Go to Contacts List
2. Click on Import Contacts
3. Import a file with the following information

Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3

4. Look at the contacts. Each contact will have the same email address.

#### Context

We cannot import our contacts into a new installation.

#### Your Environment

* SuiteCRM Version used: 7.9.12. (It was working in 7.9.9 before I upgraded)
* Browser name and version Firefox 58.0.2 (64-bit) On Mac
* Environment name and version  PHP 7 
* Operating System and version: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When importing contacts via the "Import Contacts" method each contact is saved with the first line's email address. The same email address is saved for more than the correct contact.

## Motivation and Context

Issue reference: #5197 

## How To Test This

1. Fresh install and then check that the accounts list-view has been correctly populated.
2. Enter contacts module and click "import"
3. Import a csv with the following data:
Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: include/SugarEmailAddress/SugarEmailAddress.php [hunk 1]
```diff
@@ -103,7 +103,7 @@ public function handleLegacySave($bean)
             || !isset($_REQUEST[$bean->module_dir . '_email_widget_id'])
             || !isset($_REQUEST['massupdate'])
         ) {
-            if (empty($this->addresses)) {
+            if (empty($this->addresses) || (!empty($bean->email1))) {
```
Comment (PedroErnst) [inline include/SugarEmailAddress/SugarEmailAddress.php]: I'm wondering if there could go something wrong here, eg what will happen if a bean has addresses and email1 is set? 

It will clear all the addresses and create new from the legacy address data, which I think is not as complete.

Not 100% but I think this line could cause data loss?

Comment (samus-aran) [reply include/SugarEmailAddress/SugarEmailAddress.php]: Seems to be a regression issue - Dillon do you have a commit of what was changed in this file?

File: data/SugarBean.php [hunk 2]
```diff
@@ -1919,7 +1919,15 @@ public function save($check_notify = false)
             foreach ($this->email_addresses_non_primary as $mail) {
                 $this->emailAddress->addAddress($mail);
             }
-            $this->emailAddress->save($this->id, $this->module_dir);
+            $this->emailAddress->saveEmail(
```
Comment (samus-aran) [inline data/SugarBean.php]: Same here - Is this regression?

Comment (Dillon-Brown) [reply data/SugarBean.php]: $this->emailAddress is deprecated. Original issue is from this commit: https://github.com/salesagility/SuiteCRM/pull/5118/commits/0f01e1a17a3401dff4dadea261e661f85eac472e

**Comment by QuickCRM** [comment]
Hi,

It looks like the problem is only partially fixed:
If you import
test1@domain.com, First1, Last1
, First2, Last2
test3@domain.com, First3, Last3

First2,Last2 will have test1@domain.com as email address.

File: include/SugarEmailAddress/SugarEmailAddress.php (hunk 1 above)
Comment (clemente-raposo) [reply include/SugarEmailAddress/SugarEmailAddress.php:106]: @PedroErnst you were right here, this is causing issue https://github.com/salesagility/SuiteCRM/issues/7842

@mattlorimer, this needs to be reverted and fixed in another place
