### PR TITLE
Fix #10264 Error Assigned_user_name SearchView.tpl (`{php}` tag now crashes Smarty 4)

### LINKED ISSUE #10264: Error Assigned_user_name SearchView.tpl [SMARTY 4]
7.14 brings SMARTY to version 4.
{php} is now crashing the Search Popup in /include/SugarFields/Fields/Assigned_user_name/SearchView.tpl

#### Expected Behavior
Pop up display the frm and the list of records.

#### Actual Behavior
Pop crashes and show a blank page.

#### Possible Fix
No idea

#### Steps to Reproduce

1. Edit any popupdefs : /custom/modules/{modulename}/metadata/popupdefs.php
2. Add the following field in the searchdefs:
`  'created_by' => 
  array (
    'type' => 'assigned_user_name',
    'label' => 'LBL_CREATED',
    'width' => '10%',
    'name' => 'created_by',
  ),`
4. Repair
5. Go to the subpanel of the module, click on select.
6. The pop up crash and show a blank page
7. In the logs: `[FATAL] Exception in Controller: Syntax error in template "file:/cache/themes/SuiteP/modules/{modulename}/SearchForm_popup_query_form.tpl"  on line 90 "{php}$this->_tpl_vars['user_options'] = get_user_array(false);{/php}" unknown tag 'php'`

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

### PR DESCRIPTION
**Pull request by chris001**
Fixes #10264 

The `{php}` tag was removed from Smarty 3.1.
There was an omission in converting the Smarty code in this code to be compatible with current Smarty version used, in the current maintenance release 7.14.2.

Somehow, this `{php}` tag was left in this template file.  Smarty 3.1 has removed `{php}` tags.  It must be replaced with Smarty 3.1+ compatible code.

## Description

Replace old `{php}` tag code with new code that works with Smarty 3.1+.

## Motivation and Context

The software will crash on this screen because `{php}` tag is no longer supported by current Smarty version used.

## How To Test This

Run Suite 7.14.2 and go to this screen.  It should fail.
Apply this fix and go to this screen.  It should work.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @chris001,

thank you for this PR,

I'm afraid I'm not able to apply a current fix: 

Having  suggested changes in the codebase I remove the  application and the browser cache:
image

image

image

I can't get the popup view rendered:
image

Additional check: 
commenting out given line gives me an opportunity to get the view (without options in select as I don't pass them on the tpl): 

image

image

Thanks in advance for your response!

**Comment by chris001** [comment]
Sorry for that @serhiisamko091184
I reworked the fix, tested it locally on Bitnami Suite 7.14.1 on PHP 8.1, and it works now.
fix 10264 smarry php tag crashes smarty4
Please re-check on your side.

**Review by jack7anderson7 — APPROVED** [review]

File: include/SearchForm/SearchForm2.php [hunk 1]
```diff
@@ -186,7 +186,7 @@ public function display($header = true)
         $this->th->ss->assign('action', $this->action);
         $this->th->ss->assign('displayView', $this->displayView);
         $this->th->ss->assign('viewTab', $this->getViewTab());
-
+        $this->th->ss->assign('user_options', get_user_array(false)); // Fix https://github.com/salesagility/SuiteCRM/issues/10264
```
Comment (adriangibanelbtactic) [inline include/SearchForm/SearchForm2.php:189]: I don't think we should fill Suitecrm with comments with each one of the issues.
That's what Git history is for.

File: include/SugarFields/Fields/Assigned_user_name/SearchView.tpl [hunk 2]
```diff
@@ -40,5 +40,5 @@
 
 *}
 {{capture name=display_size assign=size}}{{$displayParams.size|default:6}}{{/capture}}
-{php}$this->_tpl_vars['user_options'] = get_user_array(false);{/php}
+
```
Comment (adriangibanelbtactic) [inline include/SugarFields/Fields/Assigned_user_name/SearchView.tpl:43]: Any reason why you add a line instead of just removing the original line?

**Review by johnM2401 — DISMISSED** [review]
LGTM from testing perspective, Able to see filters that were previously broken by this issue.
Can filter on both Created By / Modified By on Basic & Advanced views.

**Review by mattlorimer — APPROVED** [review]
LGTM 👍🏻
