### PR TITLE
Fix #9668 - It is not possible to use a custom template for password change

### LINKED ISSUE #9668: It is not possible to use a custom template for password change
#### Issue

It is not possible to use a custom template for password change. This does not allow changing the organization's logo, nor applying other improvements without modify the suitecrm core.

#### Expected Behavior

If a custom template has been created, on the path `custom/modules/users/changepassword.tpl` it should be able to be used.

#### Actual Behavior

This template cannot be used, although it exists.

#### Steps to Reproduce

1. Look at the file `modules/Users/Changenewpassword.php` and see that only path `modules/Users/Changenewpassword.tpl` is enabled.

#### Context

It is important that the organization's logo and other aspects related to design can be customized, to offer a good corporate image.
#### Your Environment

* SuiteCRM Version used: 7.12.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Versión 103.0.5060.114 (Build oficial) (64 bits)
* Environment name and version (e.g. MySQL, PHP 7): MaríaDB, PHP 7.3
* Operating System and version (e.g Ubuntu 16.04): KDE Neon 5.25

### PR DESCRIPTION
**Pull request by SinergiaCRM**
## Description
- resolve #9668

File `modules/Users/changepassword.php` has been modified to use, if there is, a custom template for password change.

## Motivation and Context

This change allows to customize the organization logo, as well as modify other aspects of appearance or content of the password change screen.

## How To Test This

1. Clone template `modules/Users/Changenewpassword.tpl` to `custom/modules/Users/Changenewpassword.tpl`
2. Change some HTML element in the new template to verify what applies after the change.
3. Enable  _Forgot Password feature_ in admin área 
4. Logout & click in _Forgot Password?_ link.
5. Force a password change in Suitecrm to check the appearance of the password change screen and verify that the changes are applying.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Users/Changenewpassword.php [hunk 1]
```diff
@@ -191,5 +191,10 @@
     $sugar_smarty->assign("KEY", $_REQUEST['key']);
 }
 
-$sugar_smarty->display('modules/Users/Changenewpassword.tpl');
+if (file_exists('custom/modules/Users/Changenewpassword.tpl')) {
```
Comment (pgorod) [inline modules/Users/Changenewpassword.php:194]: I suggest replacing this entire block with
```php
$sugar_smarty->display(get_custom_file_if_exists(modules/Users/Changenewpassword.tpl));
```

Comment (SinergiaCRM) [reply modules/Users/Changenewpassword.php]: Thank you, better according to your proposal.
Changed

**Review by clemente-raposo — APPROVED** [review]
LGTM

**Review by jack7anderson7 — APPROVED** [review]
