### PR TITLE
Fixed #4133 - 7.9.4 Email Display Name Doesn't Appear for Recipient

### LINKED ISSUE #4133: 7.9.4 Email Display Name Doesn't Appear for Recipient
When sending email from 7.9.4 the Display name does not display for the recipient of the email

#### Issue

When sending email from 7.9.4 the Display name does not display for the recipient of the email, e.g. When sending a message from Charlie Woodbridge <cwoodbridge@mail.com>, the recipient only see cwoodbridge@mail.com in from data.

From: <cwoodbridge@mail.com>
X-Google-Original-From: <cwoodbridge@mail.com>

However, if you send a test message from suitecrm, the display name is displayed for the recipient as per normal practice, e.g. when sending test message the recipient sees  in the From field.

From: SuiteCRM <cwoodbridge@mail.com>
X-Google-Original-From: SuiteCRM <cwoodbridge@mail.com>

Temporary solution
Change line 2718 in /var/www/html/modules/Emails/Email.php
$mail->FromName = $current_user->getPreference('mail_fromname');
for
$mail->FromName = 'your name'; //$current_user->getPreference('mail_fromname');

#### Expected Behavior

 display for the recipient of the email
#### Actual Behavior

not  display the recipient of the email
## Steps to Reproduce

1. Compose Email
2. Send Mail 
3.
4.

#### Context

HIGH priority
#### Your Environment

SuiteCRM Version used: 7.9.4
Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
Environment name and version (e.g. MySQL, PHP 7):
Operating System and version (e.g Ubuntu 16.04):

### PR DESCRIPTION
**Pull request by Dillon-Brown**
Task: SCRM-764

## Description

In order to reply to an email you will also need PR #4056 and #4059

When sending email from 7.9.4 the Display name does not display for the recipient of the email, e.g. When sending a message from Charlie Woodbridge cwoodbridge@mail.com, the recipient only see cwoodbridge@mail.com in from data.

From: cwoodbridge@mail.com
X-Google-Original-From: cwoodbridge@mail.com

The correct format as seen when sending a test email is:

From: SuiteCRM cwoodbridge@mail.com
X-Google-Original-From: SuiteCRM cwoodbridge@mail.com

## Motivation and Context

This change allows the email composer to check "from_addr_name" for a name instead of only checking "from_name" which in the previous example would have been NULL.

Issue reference: #4133

## How To Test This

1. Receive an email.
2. Click "Reply" in the email detailview actions dropdown.
3. Send the email.
4. Ensure the sent mail contains the correct format as seen when sending a test email.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/Emails/Email.php [hunk 1]
```diff
@@ -2698,7 +2699,10 @@ public function send()
         // FROM NAME
         if (!empty($this->from_name)) {
             $mail->FromName = $this->from_name;
-        } else {
+        } elseif (!empty($this->from_addr_name)) {
+            $mail->FromName = $this->from_addr_name;
+        }
+        else {
```
Comment (daniel-samson) [inline modules/Emails/Email.php]: psr-2: else should be inline with the {
