### PR TITLE
Fixed #6866 - 7.10.12 Auto Import of Emails not working

### LINKED ISSUE #6866: 7.10.12 Auto Import of Emails not working
Fresh install of 7.10.12 Auto Import of group mail account no longer working.
#### Issue

Upgraded from 7.10.7 where this was working fine.  

#### Expected Behavior
screenshot 2019-01-30 18 26 47

#### Actual Behavior
screenshot 2019-01-30 18 43 59
I can manually import but auto import stoped working.   I also applied the SuiteCRM-hotfix-7.10.x which corrected the listview no records problem. But not the auto import.
No errors in logs related to this issue.

#### Steps to Reproduce
1. Install 7.10.12
2. Create group inbound email account and checked 
screenshot 2019-01-30 18 36 10

3.Review the Emails module listview

#### Context

Auto import of emails creates records in the system to be processed without this all automation is not working. 

#### Your Environment

* SuiteCRM Version used: 7.10.12
* Browser name and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* Environment name and version MySQL , PHP 7): PHP 7.0.32, MYSQL 5.7.25
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04.1

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixes an issue with auto-import not importing emails due to BADCHARSET.

## Motivation and Context

Issue reference: #6866 

## How To Test This

1. Setup group inbound email with auto-import.
2. Setup cron.
3. Receive emails to this account from exchange and non-exchange servers and check both emails import correctly.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: include/Imap/ImapHandler.php [hunk 1]
```diff
@@ -717,16 +717,26 @@ public function rfc822ParseHeaders($headers, $defaulthost = "UNKNOWN")
...
 
-        $ret = imap_search($this->getStream(), $criteria, $options, $emailCharset);
+        try {
+            $ret = imap_search($this->getStream(), $criteria, $options, $emailCharset);
+        } catch (Exception $e) {
+            if (strpos($e, ' [BADCHARSET (US-ASCII)]')) {
+                LoggerManager::getLogger()->debug("Encoding changed dynamically from {$emailCharset} to US-ASCII");
+
+                $emailCharset = 'US-ASCII';
+                $ret = imap_search($this->getStream(), $criteria, $options, $emailCharset);
```
Comment (gymad) [inline include/Imap/ImapHandler.php]: unhandled case, return value from imap_search could be:
"Return FALSE if it does not understand the search criteria or no messages have been found."

Comment (Dillon-Brown) [reply include/Imap/ImapHandler.php]: @gymad There's a check for this on line 735

**Comment by Mac-Rae** [comment]
Assessed :+1:
