### PR TITLE
Fixed #4046 - 7.9.4 - imported emails are not auto related to related records when you reply to/reply to all/ forward them

### LINKED ISSUE #4046: 7.9.4 - imported emails are not auto related to records on reply to/reply to all/ forward to actions
#### Issue

When you import email to some record, for example Account.. 

When you on reply to/reply to all/ forward to somebody, the relate field is empty... only first part is chooses (like for our example account) more on image...

account_import

#### Expected Behavior

If email is imported to some record, i want if i reply to/reply to all/ forward to that will auto related to same main record

#### Actual Behavior

You must again manually choose the record in relate to field. 

#### Steps to Reproduce

1. Import email to record
2. Open email in detail view
3. Choose one action: reply to/reply to all/ forward to
4. Check if is relate to field filled by record to which was email imported

#### Your Environment

* SuiteCRM Version used: Official SuiteCRM demo 7.9.4

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

When you import email to a record like an Account. The reply to/reply to all/ forward options on the imported email do not auto-populate the related to field.

## Motivation and Context

Issue reference: #4046 

## How To Test This

1. Import email and relate it to an account
2. Open email in detail view
3. Choose one action: reply to/reply to all/ forward to
4. Check if is relate to field is auto-populated

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/Emails/EmailsController.php [hunk 1]
```diff
@@ -659,10 +660,12 @@ public function composeBean($request, $mode = self::COMPOSE_BEAN_MODE_UNDEFINED)
             // Move email addresses from the "from" field to the "to" field
             $this->bean->to_addrs = $this->bean->from_addr;
             $this->bean->to_addrs_names = $this->bean->from_addr_name;
+            $this->bean->parent_name = $parent_name;
         } else {
```
Comment (PedroErnst) [inline modules/Emails/EmailsController.php]: $parent_name could be uninitialized

File: modules/Emails/EmailsController.php [hunk 2]
```diff
@@ -659,10 +660,12 @@ public function composeBean($request, $mode = self::COMPOSE_BEAN_MODE_UNDEFINED)
...
             if ($mode === self::COMPOSE_BEAN_MODE_FORWARD) {
                 $this->bean->to_addrs = '';
                 $this->bean->to_addrs_names = '';
+                $this->bean->parent_name = $parent_name;
             } else {
```
Comment (PedroErnst) [inline modules/Emails/EmailsController.php]: $parent_name could be uninitialized

**Comment by samus-aran** [comment]
@Dillon-Brown Any further forward with this? Still and issue? Still a Fix?
