### PR TITLE
Fix #4736 Make Template Sample use absolute Logo URL

### LINKED ISSUE #4736: Email Quotation do not rewrite image url so you can't see it in email
#### Issue

 
When you email a Quotation with a template you create with PDF Template, and this template includes a local image like: "themes/default/images/company_logo.png" this URL image is sent via email.... It should be rewritten like: https://demo.suitecrm.nube.coop/themes/default/images/company_logo.png
If not, the image is not loaded in the email.

#### Expected Behavior

The img tag shoud be something like:

``

#### Actual Behavior

The img tag is:

``

#### Steps to Reproduce

1. Create a Quote Template, and load an sample.

pdf_templates_1

2. You can verify the img tag and its url

pdf_templates_2

3. Send a Quotation by email, and verify that the image is shown:

pdf_templates_3

4. When you receive the email the image is not shown:

pdf_templates_4

5. If you verify email code, you will see the img tag is no rewritten:

``

#### Your Environment

* SuiteCRM Version used: 7.9.x and 7.10-beta2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 57
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 5.6 and PHP 7.0
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04 and 17.10

### PR DESCRIPTION
**Pull request by PedroErnst**
Modified the default template samples for AOS_PDF_Templates module to use the absolute path to the CRM logo instead of the relative path to avoid it not showing up in emails.

## Motivation and Context

Issue #4736

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/AOS_PDF_Templates/samples/smpl_Account_Sample.php [hunk 1]
```diff
@@ -5,13 +5,15 @@ function getType() {
 		}
 
 		function getBody() {
-		global $locale;
-		$d_image = explode('?',SugarThemeRegistry::current()->getImageURL('company_logo.png'));
+        global $locale, $sugar_config;
+        $baseUrl = $sugar_config['site_url'];
+        $logoUrlArr = explode('?',SugarThemeRegistry::current()->getImageURL('company_logo.png'));
+        $logoUrl = $baseUrl . '/' . $logoUrlArr[0];
```
Comment (zoltankocsardi) [inline modules/AOS_PDF_Templates/samples/smpl_Account_Sample.php]: Can you create a new service class for the logoUrl?

Comment (PedroErnst) [reply modules/AOS_PDF_Templates/samples/smpl_Account_Sample.php]: Updated
