### PR TITLE
Fix #5918 Activity Stream elapsed time calculation

### LINKED ISSUE #5918: After upgrade from 7.9.9 to 7.10.5 all activity stream items say "0 seconds ago"
#### Issue

After upgrade from 7.9.9 to 7.10.5 all activity stream items say "0 seconds ago"

#### Expected Behavior

Should have correct time since the item was created

#### Actual Behavior

Only shows "0 seconds ago"

#### Steps to Reproduce

1. Upgrade from 7.9.9 to 7.10.5
2. Look on home page
3. Look at items created before upgrade as well as ones after

#### Context

Don't know when the activity is form

#### Your Environment

* SuiteCRM Version used: 7.10.5
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 66.0.3359.170
* Environment name and version (e.g. MySQL, PHP 7): MySql , PHP 5.6.x
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

### PR DESCRIPTION
**Pull request by mattlorimer**
The fix in 7.10.5 doesn't fully fix this issue

## Description
This fix correctly calculated the time elapsed and handles invalid start dates

## How To Test This
Check the Activity Stream time elapsed calculates correctly regardless of date/time settings 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by Dillon-Brown** [comment]
Assessed

File: modules/SugarFeed/SugarFeed.php [hunk 1]
```diff
@@ -496,13 +496,17 @@ static function getTimeLapse($startDate)
...
-        $timedate->getInstance()->userTimezone();
-        $currentTime = $timedate->now();
+        $nowTs = $timedate->getNow()->ts;
 
-        $first = strtotime($currentTime);
-        $second = strtotime($startDate);
+        if (null !== ($userStartDate = $timedate->fromUser($startDate))) {
+            $userStartDateTs = $userStartDate->ts;
+        } else {
+            LoggerManager::getLogger()->warn('Invalid $startDate)');
```
Comment (PedroErnst) [inline modules/SugarFeed/SugarFeed.php]: Maybe a stray closing parenthese inside the string?

**Comment by Dillon-Brown** [comment]
Assessed

**Comment by pgorod** [comment]
Dillonm maybe this needs to be done for 7.8.x?

User [in Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19273-activity-stream-7-10-5#77627) says so

> Does anyone know if there was reason this was not also changed in Version 7.8.26? Since at least 7.8.22, the activity stream read 0 Hours 0 Minutes ago for all entries new and historic. I replaced the "static function getTimeLapse($startDate)" function with the pull request #6033 code and the new and historic times are now correctly displayed again.

**Comment by pgorod** [comment]
For reference, the 7.8.x duplicate of this PR is already done, it's #6937

**Comment by MyBlissIT** [comment]
I am struggling to locate the exact fix... please assist

**Comment by Dillon-Brown** [comment]
@MyBlissIT The latest fix for activity stream is here: #8005
