### PR TITLE
fixes #7308 - Sub-Theme changes don't always update

### LINKED ISSUE #7308: Sub-Theme changes don't always update
#### Issue

When editing a sub-theme, either custom or default the robotask to recompile SASS runs but style.css does not update.

#### Expected Behavior
style.css updates with the recently added scss classes.

#### Actual Behavior

robo task `build:suitep` runs but fails to over write style.css and never looks for custom themes in the `custom/themes/` directory. Manual deletion of style.css is required in most cases.

#### Possible Fix

I am prepared to submit an initial merge request containing an update to the `build:suitep` robotask. Search `/css` for subtheme style's remove the old file compile a new one. look for possible themes in the `/custom/theme` directory.

### PR DESCRIPTION
**Pull request by mcarpenterjr**
Removes old style sheets for sub-themes of SuiteP. Gets dynamic with searching the stock SuiteP dir and `/custom/them` dir.
fixes #7308

## Description

Removed the hardcoded sub-theme references and dynamically search the `theme/SuiteP/css/` directory for any possible directories that may contain any `style.css` or `style.scss` indicating they are a subtheme definition. If a `style.css` file is found remove it in prep for the new file to be compiled. This goes the same for the `custom/theme/` directory also. Theme directories are stored in variables so they can be updated later or possibly specified as params in the future.

Updated the `buildSuitePColorScheme()` function to accept an additional `$location` parameter with a default definition. This allows flexibility when directing what subthemes to compile.

## Motivation and Context

Recently ran into multiple issues with themes not compiling style sheets properly and custom themes not compiling into an actual theme. Initially for either permission reasons or some other error `style.css` was not being overwritten after it had been compiled from scratch, I found the simplest solution to be, remove the file and then recompile. I also noticed the automated build task would not recognize any custom subthemes I had created in either the `custom/themes` dir or in the stock `themes` dir. I found the issues with the custom subtheme dir only after I had "forgotten" a custom theme had been created there and then left and never recompiled to the new changes.

## How To Test This

Create a copy of an existing subtheme, or make changes to a subtheme's SASS files, then run the robo task `build:suitep` all changes should take hold.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
I believe you're supposed to open branches targeting `hotfix` (for 7.11) or `7.10.x-hotfix` (for 7.10 _and_ 7.11), not `develop`.

**Comment by mcarpenterjr** [comment]
Inside [CONTRIBUTING.md](https://github.com/salesagility/SuiteCRM/blob/master/.github/CONTRIBUTING.md) it states 

> Changes that can be considered a new feature or enhancement should be made to the develop branch instead of the hotfix or hotfix-7.8.x. branch

I believe this is less a bug fix and more an enhancement, either way, I would be more than happy to retarget to the hotfix branches if required.

File: lib/Robo/Plugin/Commands/BuildCommands.php [hunk 1]
```diff
@@ -38,54 +38,74 @@
...
-        }
-        $this->say('Compile SuiteP Theme (SASS) Complete');
+  use loadTasks;
+  use RoboTrait;
+  // define public methods as commands
+  /**
+   * Build SuiteP theme
+   * @params array $opts optional command line arguments
+   * color_scheme - set which color scheme you wish to build
+   * @throws \RuntimeException
```
Comment (Dillon-Brown) [inline lib/Robo/Plugin/Commands/BuildCommands.php]: Should be ```@param array $opts```.

File: lib/Robo/Plugin/Commands/BuildCommands.php [hunk 2]
```diff
@@ -38,54 +38,74 @@
...
-            }
-        } else {
-            $this->buildSuitePColorScheme($this->opts['color_scheme']);
-        }
-        $this->say('Compile SuiteP Theme (SASS) Complete');
+  use loadTasks;
+  use RoboTrait;
+  // define public methods as commands
+  /**
+   * Build SuiteP theme
```
Comment (Dillon-Brown) [inline lib/Robo/Plugin/Commands/BuildCommands.php]: PSR-2 across this file, using 2 spaces instead of 4.

File: lib/Robo/Plugin/Commands/BuildCommands.php [hunk 3]
```diff
@@ -38,54 +38,74 @@
...
+   * @params array $opts optional command line arguments
+   * color_scheme - set which color scheme you wish to build
+   * @throws \RuntimeException
+   */
+  public function buildSuitep(array $opts = ['color_scheme' => ''])
+  {
+    $this->say('Compile SuiteP Theme (SASS)');
+    if (empty($this->$opts['color_scheme'])) {
+      /** Look for Subthemes in the SuiteP theme Dir **/
+      $std = "themes/SuiteP/css/";
```
Comment (Dillon-Brown) [inline lib/Robo/Plugin/Commands/BuildCommands.php]: Single quotes should be preferred over double.

File: lib/Robo/Plugin/Commands/BuildCommands.php [hunk 4]
```diff
@@ -38,54 +38,74 @@
...
+      $this->locateSubTheme($std);
+      /** Look for Subthemes in the custom/theme Dir **/
+      // Good opportunity to refactor here.
+      // Does the same as above just looks in the custom directory.
+      $ctd = "custom/themes/SuiteP/css/";
```
Comment (Dillon-Brown) [inline lib/Robo/Plugin/Commands/BuildCommands.php]: Single quotes should be preferred over double.

File: lib/Robo/Plugin/Commands/BuildCommands.php [hunk 5]
```diff
@@ -38,54 +38,74 @@
...
+      . $os->toOsPath("{$location}{$colorScheme}/style.css");
+    $this->_exec($command);
+  }
+  /**
+   * @param string $directory
+   */
+  private function locateSubTheme($directory) {
+    if (is_dir($directory) && $dir = opendir($directory)) {
+      while(false !== ($file = readdir($dir))) {
+        if (filetype($directory . $file) === 'dir' && file_exists($directory . $file . "/style.scss")) {
```
Comment (Dillon-Brown) [inline lib/Robo/Plugin/Commands/BuildCommands.php]: More single quotes and PSR-2.

**Comment by Dillon-Brown** [comment]
You can ignore Travis btw, just flaky tests unrelated to this PR. Nice work!

**Comment by mcarpenterjr** [comment]
Thank You! I look forward to contributing more, I'll have to update my formatter going forward! Sorry about the mess, new to github's PR workflow.

**Comment by cameronblaikie** [comment]
Assessed :+1:
