### PR TITLE
FIXED #7319 - Activity Stream dashlet "reply" function doesn't appear to do anything

### LINKED ISSUE #7319: Activity Stream dashlet  "reply" function doesn't appear to do anything
#### Issue
 
When on the activity stream dashlet, there is a reply button, you can enter a reply and it will show as normal but when you filter the activity stream to a module the reply doesn't show up.

#### Expected Behavior

For the reply to be visible. 
#### Actual Behavior

no reply is visible when filtered to a module 

#### Steps to Reproduce

1. Click Reply and see an input box underneath the entry you want to reply to.
2. Enter Text and Click POST button
3. Dashlet refreshes and you see the Reply underneath the entry with a user's profile picture.

Screenshot from 2019-05-29 10-00-48

#### Your Environment

* SuiteCRM Version used: 7.11.4
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

### PR DESCRIPTION
**Pull request by cameronblaikie**
When on the activity stream dashlet, there is a reply button, you can enter a reply and it will show as normal but when you filter the activity stream to a module the reply doesn't show up.

## Motivation and Context

https://github.com/salesagility/SuiteCRM/issues/7319 

## How To Test This

1. Click Reply and see an input box underneath the entry you want to reply to.
2. Enter Text and Click POST button
3. Dashlet refreshes and you see the Reply underneath the entry with a user's profile picture.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php [hunk 1]
```diff
@@ -596,7 +596,8 @@ public function getPostForm()
     {
         global $current_user;
 
-        if ((!empty($this->selectedCategories) && !in_array('UserFeed', $this->selectedCategories))
+
+        if ((!empty($this->selectedCategories) && !in_array('User Feed', $this->categories))
```
Comment (Dillon-Brown) [inline modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php]: Unnecessary parenthesis. We should also provide a third parameter for ```in_array``` to provide type safety.
```suggestion
        if (!empty($this->selectedCategories) && !in_array('User Feed', $this->categories, true)
```

**Comment by Mac-Rae** [comment]
Assessed :+1:

**Comment by Mac-Rae** [comment]
Reassessed :+1:
