### PR TITLE
Fix #9660 - Copy only select files to custom/working directory

### LINKED ISSUE #9660: Imported Customizations cause issues with Studio views
#### Issue

Imported module customizations via the module loader copy files to the "custom/working" directory. This directory is used to store studio changes that have been saved but not deployed.

All metadata is copied to this directory, except for listviewdefs.php, regardless if it is in the custom/working directory of the exported module.

This causes an issue where Studio loads in this working metadata file for dashletviewdefs and never overwrites or deletes it because the working directory is only used for detail view, edit view and quickcreate view.

#### Expected Behavior
Files should be copied to the custom/working directory if there is a chance that the file could exist on the server in the custom/working directory.(editviewdefs.php, detailviewdefs.php, quickcreatedefs.php)

#### Actual Behavior
All metadata files except listviewdefs.php are copied to the custom/working directory

#### Possible Fix
Only copy editviewdefs.php, detailviewdefs.php, quickcreatedefs.php to the custom/working directory.

#### Steps to Reproduce

1. Go to Studio and make a customization to cases->layouts->defaults->SuiteCRM Dashlet->SuiteCRM Dashlet Search to create a custom/modules/Cases/metadata/dashletviewdefs.php file.
2. Go back to Studio homepage and click "Export Customizations"
3. Name the export file and choose the cases module and click export
4. Use module loader to install the customizations from step 3
5. Try to make a change to cases->layouts->default->SuiteCRM Dashlet->SuiteCRM Dashlet Search
6. The change made will not update in Studio.

#### Context
Customizations imported from a different SuiteCRM instance cause this Studio issue until the affected files are deleted from the working directory.

#### Your Environment

* SuiteCRM Version used: 7.12.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 102.0 64-bit
* Environment name and version (e.g. MySQL, PHP 7): php 7.4
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 20.04.4 LTS

### PR DESCRIPTION
**Pull request by ojs87**
## Description
From issue https://github.com/salesagility/SuiteCRM/issues/9660

Imported module customizations via the module loader copy files to the "custom/working" directory. This directory is used to store studio changes that have been saved but not deployed.

All metadata is copied to this directory, except for listviewdefs.php, regardless if it is in the custom/working directory of the exported module.

This causes an issue where Studio loads in this working metadata file for dashletviewdefs and never overwrites or deletes it because the working directory is only used for detail view, edit view and quickcreate view.

## Motivation and Context
Imported customizations cause Studio to load the wrong dashlet views.

## How To Test This
1. Go to Studio and make a customization to cases->layouts->defaults->SuiteCRM Dashlet->SuiteCRM Dashlet Search to create a custom/modules/Cases/metadata/dashletviewdefs.php file.
2. Go back to Studio homepage and click "Export Customizations"
3. Name the export file and choose the cases module and click export
4. Use module loader to install the customizations from step 3
5. Try to make a change to cases->layouts->default->SuiteCRM Dashlet->SuiteCRM Dashlet Search
6. The change made will not update in Studio.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by jack7anderson7 — APPROVED** [review]

File: modules/ModuleBuilder/MB/MBPackage.php [hunk 1]
```diff
@@ -561,18 +561,18 @@ private function getCustomFieldsManifestForModule($module, &$installdefs)
     private function getCustomMetadataManifestForModule($module, &$installdefs)
     {
         $meta_path = 'custom/modules/' . $module . '/metadata';
+        $working_array = [
+            'editviewdefs.php',
+            'detailviewdefs.php',
+            'quickcreatedefs.php'
+        ];
```
Comment (clemente-raposo) [inline modules/ModuleBuilder/MB/MBPackage.php:568]: Hi @ojs87, @jack7anderson7 why are we only including these files?

Comment (clemente-raposo) [reply modules/ModuleBuilder/MB/MBPackage.php:568]: @jack7anderson7 pointed out what has been stated on the PR description.

> All metadata is copied to this directory, except for listviewdefs.php, regardless if it is in the custom/working directory of the exported module.

> This causes an issue where Studio loads in this working metadata file for dashletviewdefs and never overwrites or deletes it because the working directory is only used for detail view, edit view and quickcreate view.
