### PR TITLE
Fixed #8472 - No or not complete Searchresults using elasticsearch engine

### LINKED ISSUE #8472: No or not complete Searchresults using elasticsearch engine
#### Issue

I got no or incomplete Searchresults when using elasticsearch engine.
I configured Opportunities,Accounts,Contacts,Calls,AOS_Contracts for global search.
I cleaned the elasticsearch index and started full indexing.
In search_index.log I got no errors and all is finished:
Finished Opportunities. Processed 10969 Records [] [
Finished Accounts. Processed 14587 Records [] []
Finished Contacts. Processed 6831 Records [] []
Finished Calls. Processed 1544 Records [] []
Finished Tasks. Processed 28127 Records [] []
Finished AOS_Contracts. Processed 407 Records [] []
6 modules, 62465 records and 1818702 fields indexed in 122.238 s [] []

In elasticsearch.log, Apache error.log and suitecrm logs are no errors

When I now search I get always different outputs and often no output:
ie: When i searched for Raiffeisen. I get only Accounts, and no other entries from other modules.
grafik

When I look for Raiff only, i get no results:
grafik

When I look for Raiff* , I get only Accounts again but more than the fist search result:
grafik
 
When I search for a Opportunity I get always no results. When I seach for users, I get sometimes a result with some modules but not always

 The only error I can see is in apache error.log:
 PHP Recoverable fatal error:  Object of class Link2 could not be converted to string in /var/www/sugarcrm/lib/Search/SearchResults.php on line 213, referer: https://XXXX/sugarcrm/index.php?action=Search&search-query-string=Raiff*&search-query-size=10&search-query-from=10&search-engine=ElasticSearchEngine 

#### Expected Behavior

All entries and should be displayed 
#### Actual Behavior

incomplete results
#### Possible Fix

?
#### Steps to Reproduce

?
#### Your Environment

* SuiteCRM Version used: 7.11.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): actual Browsers
* Environment name and version (e.g. MySQL, PHP 7): 7.2
*Operating System and version (e.g Ubuntu 16.04): ubuntu 18.04
* elasticsearch 5.6.16

### PR DESCRIPTION
**Pull request by tsitle**
## Description

Issue reference: #8472
Issue reference: #7742

This PR adds support for the config values
	$GLOBALS['sugar_config']['search_wildcard_char']
	and
	$GLOBALS['sugar_config']['search_wildcard_infront']
to ElasticSearchEngine::createSearchParams().
And it fixes resolving related bean IDs in SearchResults::getRelatedId() when
there is more than one level of relationships.

## Motivation and Context

Using the ElasticSearchEngine can cause fatal PHP errors (and therefor resulting
in incomplete search results) and
search results returned by the ElasticSearchEngine can appear incomplete
when one expects the default search wildcard character '%' to work as it would
when using filters (SQL) or the legacy 'Advanced Search' engine.

## How To Test This

1. Search Engine configuration: put the following config values in the `config_override.php`:
```
$sugar_config['search_wildcard_char'] = '%';
$sugar_config['search_wildcard_infront'] = true;  // or false if you prefer
$sugar_config['aod']['enable_aod'] = false;
$sugar_config['search']['controller'] = 'Search';
$sugar_config['search']['defaultEngine'] = 'ElasticSearchEngine';
$sugar_config['search']['ElasticSearch']['enabled'] = true;
$sugar_config['search']['ElasticSearch']['host'] = '<YOUR_ES_HOST>';
```
2. Make sure the ElasticSearch server is up and running
3. If don't already have an ElasticSearch index you'll need to schedule a
full indexing via Admin panel -> Elasticsearch -> Schedule full indexing.
Wait until the scheduler job is done.
4. Enter a search term that should match at least one existing record
in the global search form at the top of the page.
E.g.: If you have a company record named "My ACME Company" try
to search for "acme" or "%acme" or "company" or "%company".
5. Create a Tasks record that is related to a Contacts record which again
is related to an Accounts record.
6. Try searching for that Tasks record

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by tsitle** [comment]
Please note that I used the "hotfix" branch as base for this PR because Elasticsearch was introduced in version 7.11 and hence is not present in the "hotfix-7.10.x" branch.

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/Search/ElasticSearch/ElasticSearchEngine.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4929882&bid=16307077)

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- lib/Search/ElasticSearch/ElasticSearchEngine.php  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4929882&bid=16307077)

**Comment by sxenny** [comment]
@tsitle 
hi

I use suitecrm 7.11.15 / Elasticsearch 5.6.10
and I fix an empty result page by your fix

BUT
I find one strange thing 
If I try to open any one-to-many relationship field on the result page I get "**Error retrieving record. This record may be deleted or you may not be authorized to view it"**

It because clicked one-to-many relationship field have the same ID with main reached record

I created a post on SuiteCRM forum https://community.suitecrm.com/t/elasticsearch-doesnt-open-any-custom-fields/76012/4?u=lyk37858

another user was able to confirm this bug

**Review by Dillon-Brown — DISMISSED** [review]

**Review by Dillon-Brown — APPROVED** [review]

**Review by Dillon-Brown — APPROVED** [review]

File: lib/Search/ElasticSearch/ElasticSearchEngine.php [hunk 1]
```diff
@@ -118,15 +119,39 @@ protected function validateQuery(SearchQuery &$query)
...
+            if ($wildcardFe !== $wildcardBe && strlen($wildcardFe) === 1) {
+                $searchStr = str_replace($wildcardFe, $wildcardBe, $searchStr);
+            }
+        }
+
+        // Add wildcard at the beginning of the search string
+        if (isset($GLOBALS['sugar_config']['search_wildcard_infront']) &&
+            $GLOBALS['sugar_config']['search_wildcard_infront'] === true && $searchStr[0] !== $wildcardBe) {
+            $searchStr = $wildcardBe . $searchStr;
+        }
```
Comment (clemente-raposo) [inline lib/Search/ElasticSearch/ElasticSearchEngine.php:139]: @Dillon-Brown @mattlorimer Minor improvement. Maybe we could simplify the above by doing.

```
        $addWildCard = $GLOBALS['sugar_config']['search_wildcard_infront'] ?? false;
        if (addWildCard === true && $searchStr[0] !== $wildcardBe) {
            $searchStr = $wildcardBe . $searchStr;
        }
```

File: lib/Search/ElasticSearch/ElasticSearchEngine.php [hunk 2]
```diff
@@ -118,15 +119,39 @@ protected function validateQuery(SearchQuery &$query)
...
+        // Wildcard character required for Elasticsearch
+        $wildcardBe = "*";
+
+        // Override frontend wildcard character
+        if (isset($GLOBALS['sugar_config']['search_wildcard_char'])) {
+            $wildcardFe = $GLOBALS['sugar_config']['search_wildcard_char'];
+            if ($wildcardFe !== $wildcardBe && strlen($wildcardFe) === 1) {
+                $searchStr = str_replace($wildcardFe, $wildcardBe, $searchStr);
+            }
+        }
```
Comment (clemente-raposo) [inline lib/Search/ElasticSearch/ElasticSearchEngine.php:133]: @Dillon-Brown @mattlorimer Minor improvemenet. Maybe we could simplify the above by doing.

```php
        $wildcardFe = $GLOBALS['sugar_config']['search_wildcard_char'] ?? '';
        if ($wildcardFe !== $wildcardBe && strlen($wildcardFe) === 1) {
            $searchStr = str_replace($wildcardFe, $wildcardBe, $searchStr);
        }
```

File: lib/Search/ElasticSearch/ElasticSearchEngine.php [hunk 3]
```diff
@@ -135,8 +160,10 @@ private function createSearchParams($query)
                 ],
             ],
         ];
+    }
 
-        return $params;
+    private function endsWith($haystack, $needle) {
```
Comment (clemente-raposo) [inline lib/Search/ElasticSearch/ElasticSearchEngine.php:165]: @Dillon-Brown @mattlorimer this method was added but does not seem to be used.

Maybe it was supposed to be used in the following?

```php
        if ((!substr_compare($searchStr, $wildcardBe, -strlen($wildcardBe))) === 0) {
            $searchStr .= $wildcardBe;
        }
```

File: lib/Search/SearchResults.php [hunk 4]
```diff
@@ -168,13 +168,18 @@ protected function updateObjLinks(SugarBean $obj, &$fieldDef)
     {
         if ($fieldDef['type'] == 'relate' && isset($fieldDef['link']) && isset($fieldDef['id_name']) && $fieldDef['id_name']) {
             $relId = $this->getRelatedId($obj, $fieldDef['id_name'], $fieldDef['link']);
-            $obj->{$fieldDef['name']} = $this->getLink($obj->{$fieldDef['name']}, $fieldDef['module'], $relId, 'DetailView');
+            if (!empty($relId)) {
+                $obj->{$fieldDef['name']} = $this->getLink($obj->{$fieldDef['name']}, $fieldDef['module'], $relId,
+                    'DetailView');
+            } else {
+                LoggerManager::getLogger()->warn('Unresolved related ID for field: ' . $fieldDef['id_name']);
+            }
```
Comment (clemente-raposo) [inline lib/Search/SearchResults.php:176]: @Dillon-Brown @mattlorimer 

Here I would keep the `LoggerManager::getLogger()->warn('Unresolved related ID for field: ` within the `getRelatedId` even if in 2 places. As it log even it the `getRelatedId` is called by other methods in the future

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 1 above)
Comment (Dillon-Brown) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php:139]: Unfortunately, there's no support for null coalescing operator in PHP 5.6 :(.

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 2 above)
Comment (Dillon-Brown) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php:133]: Same as above.

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 3 above)
Comment (Dillon-Brown) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php:165]: Ahh yeah, this can be removed. I was looking to see if we had a similar method in the utils or something and must have copied this in. We only need to do this once so we don't really need a dedicated method here. Pushed!

File: lib/Search/SearchResults.php (hunk 4 above)
Comment (Dillon-Brown) [reply lib/Search/SearchResults.php:176]: Agreed, pushed!

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 1 above)
Comment (clemente-raposo) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php:139]: ah.. ok. thanks @Dillon-Brown

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 2 above)
Comment (clemente-raposo) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php:133]: thanks!

File: lib/Search/ElasticSearch/ElasticSearchEngine.php (hunk 3 above)
Comment (clemente-raposo) [reply lib/Search/ElasticSearch/ElasticSearchEngine.php]: Thanks!

File: lib/Search/SearchResults.php (hunk 4 above)
Comment (clemente-raposo) [reply lib/Search/SearchResults.php:176]: Thanks!

Comment (clemente-raposo) [reply lib/Search/SearchResults.php:176]: @Dillon-Brown since added the logging back to the method we can remove it from here.

Comment (Dillon-Brown) [reply lib/Search/SearchResults.php:174]: Pushed

Comment (clemente-raposo) [reply lib/Search/SearchResults.php:174]: thanks!

**Comment by clemente-raposo** [comment]
code looks ok

**Review by clemente-raposo — APPROVED** [review]
code looks ok

**Review by Dillon-Brown — APPROVED** [review]
