### PR TITLE
fixed #6440 - Emails imported automatically won't allow to change the user assigned to

### LINKED ISSUE #6440: Emails imported automatically won't allow to change the user assigned to
In Group Email Account, if "Import emails automatically" is activated, it won't be possible to change the user which is assigned to or the contact which is related to.

#### Issue

For **Group Email Accounts** we can activate "Import emails automatically". The default behavior is: 

- all the messages received will be imported automatically;
- they will also be assigned to Admin user; and
- if the sender's contact is on the DB, it will be related to the proper contact, showing in the subpanels contact's page.

If I want to change the user which the message is assigned to, or the contact which it is related to, I should open the message and click Actions -> Edit. **For the messages automatically imported, the option "Edit" won't appear. Instead, it will show "Imported", as if the message was not already imported. If I try to import and click "OK", it will take me to a blank page.**

**Related question:** In our use case, we would like to activate the option "Import emails automatically" only to relate the messages automatically with the sender's contact. The automatic assign to admin user is useless for us. In previous versions, the emails would relate to the sender's contact without the need to activate "Import automatically". Since v7.10.9, the message needs to be imported in order to relate to the contact. Would it be another bug? Or it's the default behavior?

#### Expected Behavior
The messages imported automatically should show the option "Edit" in Actions menu, instead of "Import".

#### Actual Behavior
Actions menus show "Import" as if the message was not already imported. When importing, it shows a blank page and it will note change the user assigned to or the contact related to.

#### Possible Fix
Unknown

#### Steps to Reproduce
1. Create a group email account
2. For this account, activate "Import emails automatically"
3. After an email was received and imported, open it
4. In actions menu should be "Edit" instead of "import"
5. Importing takes the user to a blank page

#### Some logs
```
Mon Oct 22 17:45:59 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] Email ID is Empty
Mon Oct 22 17:46:01 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] Request ssl value not found.
Mon Oct 22 17:46:01 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Mon Oct 22 17:46:01 2018 [14162][1][WARN] There is no any workflow to run
Mon Oct 22 17:46:02 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][ERROR] Pop error level. Try to remove the error_reporting() function from your code.
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][ERROR] fromUser: Conversion of   from user format d/m/Y H:i failed
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][ERROR] Unable to find relationship emails_email_templates
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] emails_email_templates for emails_email_templates failed to load

Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] Failed to load relationship emails_email_templates while saving Emails
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] CaseUpdatesHook: saveEmailUpdate: Not a create case or wrong parent type
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] CSS File Dawn/yui.css not found
Mon Oct 22 17:46:03 2018 [14139][224b09b1-a77f-f3a5-aa82-5ad76e47e9c6][WARN] Undefined index: server_unique_key
Mon Oct 22 17:46:07 2018 [14162][1][WARN] Request ssl value not found.
Mon Oct 22 17:46:07 2018 [14162][1][WARN] Requested folder is not defined
Mon Oct 22 17:46:07 2018 [14162][1][WARN] Saving error level. Try to remove the error_reporting() function from your code.
Mon Oct 22 17:46:08 2018 [14138][1][WARN] CSS File Dawn/yui.css not found
```

#### Your Environment
* SuiteCRM Version used: 7.10.9
* Browser name and version: Chrome Version 69.0.3497.100 (Build oficial) (64 bits)
* Environment name and version: MySQL 5.7 , PHP 7.2-fpm
* Operating System and version: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by code-ph0y**
This PR will fix the importing of email issue.

## Description
This PR was created to fix the importing issue - #6440 Emails imported automatically won't allow to change the user assigned to.

## Motivation and Context
To fix the issue (see Description)

## How To Test This
1. Set up inbound email account with import emails automatically set
2. Email the inbound email account
3. Check the email address has imported correctly
4. Check that you can assign the email to a user

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: include/SugarFolders/SugarFolders.php [hunk 1]
```diff
@@ -649,11 +649,11 @@ public function getCountUnread($folderId)
     /**
      * Convenience method, pass a SugarBean
      *
-     * @param SugarBean $bean
+     * @param $bean
      *
      * @return boolean
      */
-    public function addBean(SugarBean $bean)
+    public function addBean($bean)
```
Comment (gymad) [inline include/SugarFolders/SugarFolders.php]: Why `SugarBean` should be removed?

**Comment by Mausino** [comment]
Assessed +1
