### PR TITLE
Fixed #3355 - Bad HTML in generated subpanels (Suite7 and SuiteR theme)

### LINKED ISSUE #3355: Bad HTML in generated subpanels (Suite7 and SuiteR theme)
When sub-panels are generated, the server returns invalid HTML, which results in the browser interpreting it incorrectly.

First subpanel always truncated
screenshot - 04 04 2017 - 113908

Second and other subpanels - is ok
screenshot - 04 04 2017 - 113922

Problem in file new migrated [include/SubPanel/tpls/SubPanelDynamic.tpl](https://github.com/salesagility/SuiteCRM/commits/master/include/SubPanel/tpls/SubPanelDynamic.tpl)

Smarty template (include/SubPanel/tpls/SubPanelDynamic.tpl) was added to replace xTemplate (include/SubPanel/SubPanelDynamic.html) and pagination block moved incorrectly

include/SubPanel/SubPanelDynamic.html
```
<!-- BEGIN: dyn_list_view -->
<table cellpadding="0" cellspacing="0" width="100%" border="0" class="list view subpanel-table">
<tbody>
<!-- BEGIN: list_nav_row -->
{PAGINATION}

```

include/SubPanel/tpls/SubPanelDynamic.tpl
```
{$PAGINATION}
<table cellpadding="0" cellspacing="0" border="0"  data-empty=".....
```

PAGINATION generate in include/ListView/ListViewSubPanel.php and it is assumed that it is inserted inside the table

```
$html_text = '';
$html_text .= "<tr class='pagination' role='presentation'>\n";
.....
$html_text .= "</tr>\n";
$this->smartyTemplate->assign("PAGINATION", $html_text);
```

#### Your Environment
* SuiteCRM 7.8.2
* Version 56.0.2924.87 (64-bit)

### PR DESCRIPTION
**Pull request by ale26**
see https://github.com/salesagility/SuiteCRM/issues/3355

### CODE REVIEW

File: jssource/src_files/include/SubPanel/SubPanelTiles.js [hunk 1]
```diff
@@ -282,16 +282,17 @@ function showSubPanel(child_field, url, force_load, layout_def_key) {
...
+		current_subpanel_url = url;
+		// http_fetch_async(url,got_data,request_id++);
+		var returnstuff = http_fetch_sync(url+ '&inline=' + inline + '&ajaxSubpanel=true');
+		request_id++;
+		got_data(returnstuff, inline);
+		if (SUGAR.themes.theme_name=="SuiteP"){$('#whole_subpanel_'+child_field+' .table-responsive').footable();}
+	}
+	else{
+
+		var subpanel = document.getElementById('subpanel_'+child_field);
```
Comment (daniel-samson) [inline jssource/src_files/include/SubPanel/SubPanelTiles.js]: It would be better to check it which element exists, and then make a decision based on the element. Check the theme name does not check what is actually on  the page. It provides no guarantee of the state of a subpanel. In general it is best not to check the theme name, as it increases the technical debt.

Comment (ale26) [reply jssource/src_files/include/SubPanel/SubPanelTiles.js]: I can not verify (don't have local environment).
But I checked in the console and I see that this solution will not work. *$ ('# whole_subpanel_'+child_field)* in suiteP does not contain classes ('panel panel-default sub-panel'), but this classes contains its child elements.

Your decision on technical debt may be better, but it is worse in understanding the code, which can in the future greatly complicate the debugging. Added a block of implicit behavior that relies on the names of several insignificant class names.

The best solution would be to add some kind of attribute (for example the useFooTable class for *$ ('# whole_subpanel_'+child_field))* to the themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl template and check the fact of using the FooTable plugin in the following way:
``` $('#whole_subpanel_' + child_field).hasClass('useFooTable')```

**Comment by ale26** [comment]
I answered you above, but without results. Duplicate here

@daniel-samson , viewed your changes

I can not verify (don't have local environment).
But I checked in the console and I see that this solution will not work. $ ('# whole_subpanel_'+child_field) in suiteP does not contain classes ('panel panel-default sub-panel'), but this classes contains its child elements.

Your decision on technical debt may be better, but it is worse in understanding the code, which can in the future greatly complicate the debugging. Added a block of implicit behavior that relies on the names of several insignificant class names.

The best solution would be to add some kind of attribute (for example the useFooTable class for $ ('# whole_subpanel_'+child_field)) to the themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl template and check the fact of using the FooTable plugin in the following way:
$('#whole_subpanel_' + child_field).hasClass('useFooTable')

**Comment by daniel-samson** [comment]
@ale26 That is very good idea. :+1:  If you want to add a css class to the smarty template. Then please make a pull request with your idea, and we will be happy to review your requested changes. 

The reason for not answering before is that the pull request was already merged. Since, I don't have much time to look at pull requests. I tend not to look at merged pull request, because it is already closed.

**Comment by gunnicom** [comment]
@daniel-samson You would have more time if PRs get merged. These bugs here made work for at least five times:
#3356 , #3356 , #3460 , #3467 , #4501

**Comment by ale26** [comment]
@daniel-samson created new pull request #4631

**Comment by ale26** [comment]
New [pull request](https://github.com/salesagility/SuiteCRM/pull/4631)  proposed.
