### PR TITLE
Fix #9547 - Workflow actions not saving correctly for certain field types

### LINKED ISSUE #9547: Workflow, create record, not saving parameters
Hi everybody.

I have one custom module, and also added some fields to Opportunities.

When i save a new Opportunitie this workflow creates a record of custom module if reach certain conditions.

In the “Actions” section of the workflow, I select Recod Type: {My custom module} and establish in each field what value or field it should have, as shown in the attached image.

There is a particular field called “Monto cuota” (Currency type) in which I select the field that corresponds, and then save. But then I notice that that selection is completely cleared and I can’t assign the desired field to it.

Same thing happens to a checkbox field.

Can anyone give me some help on this? i’m running Version 7.12.5 in GCP by Bitnami

#### Expected Behavior
Save correctly the given parameters to the workflow

#### Actual Behavior
Parameters are not saved in the workflow

#### Steps to Reproduce

1. Add to Opportunities module a currency field and a checkbox field
2. Create a new person type custom module
3. In the custom module create a currency field and a checkbox field
4. Relate both module one to many
5. Create a workflow that adds a record of custom module when new opportunitie is saved.

#### Context
Value in Opportunities currecny field should be saved in the custom module currency field
Value in Opportunities clheckbox field should be saved in the custom module checkbox field

High priority

#### Your Environment

i’m running Version 7.12.5 in GCP by Bitnami
* Browser name and version: Chrome Versión 99.0.4844.82 (Build oficial) (64 bits)
* Environment name and version PHP 7.4.28
* Operating System and version 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

Thanks!

### PR DESCRIPTION
**Pull request by ojs87**
## Description

Fix an issue where a workflow action of type "Field" is put through fixUpFormatting() and returns an incorrect value which is saved incorrectly. Only "Value" types should go through fixUpFormatting()

Related to issue https://github.com/salesagility/SuiteCRM/issues/9547 https://github.com/salesagility/SuiteCRM/issues/9336

Added in PR https://github.com/salesagility/SuiteCRM/pull/9238

May be able to revert this PR https://github.com/salesagility/SuiteCRM/pull/9401

## Motivation and Context
Workflow Actions of type "Field" for checkbox/date/currency are not saving as they should

## How To Test This
1. Create a Workflow on Opportunities module
2. Add an Action to create a record. 
3. Set record type to Opportunites
4. Add Field and set the values to "Amount" "Field" "Amount"
5. Save the record and open it again, the field will be set to "Amount" "Field" "None"

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Review by jack7anderson7 — APPROVED** [review]

File: modules/AOW_Actions/AOW_Action.php [hunk 1]
```diff
@@ -106,7 +106,7 @@ public function save_lines($post_data, $parent, $key = '')
                             } else {
                                 if ($post_data[$key . 'param'][$i]['value_type'][$p_id] == 'Value' && is_array($p_value)) {
                                     $param_value[$p_id] = encodeMultienumValue($p_value);
-                                }else{
+                                }elseif($post_data[$key . 'param'][$i]['value_type'][$p_id] == 'Value'){
```
Comment (clemente-raposo) [inline modules/AOW_Actions/AOW_Action.php:109]: Hi @ojs87 @jack7anderson7  could we be missing some scenarios by not including an else? (even if not calling fixUpFormatting)

Comment (ojs87) [reply modules/AOW_Actions/AOW_Action.php:109]: I didn't think it would be necessary, as the else was originally added specifically to target post_data of type "Value". The issue arose because it was also changing post_data of type "Field" which fixUpFormatting() is not designed for.

Comment (clemente-raposo) [reply modules/AOW_Actions/AOW_Action.php:109]: Hi @ojs87, thank you

**Review by clemente-raposo — APPROVED** [review]
LGTM
