### PR TITLE
Fixed #6485 - Users: Display opt-in ticks also for external email clients

### LINKED ISSUE #6485: Email Links: Opt-In ticks not shown when email client is set to external
#### Issue

When the user has set their email client to "External Email Client" all email
links lose their opt-in information (ticks).

This might be the same issue reported in #5859 where resetting the user
settings fixed the issue. It might be that the proposed workaround of
resetting just reset the email setting to "SuiteCRM Email Client".

sugar client:
good

external client:
bad

#### Expected Behavior

Changing the email client should not change the display of the email links.

#### Actual Behavior

Changing the email client removes the opt-in information.

#### Possible Fix

I'll submit a PR shortly

#### Steps to Reproduce

1. Create a contact
2. Opt-in the contact
3. Opt-in ticks are shown in the contact list
3. Got to your profile and change the email client to external
4. Go back to the contact list

#### Your Environment
* SuiteCRM Version used: 7.10.10
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 63
* Environment name and version (e.g. MySQL, PHP 7): PHP7.2
* Operating System and version (e.g Ubuntu 16.04): Centos 7

### PR DESCRIPTION
**Pull request by lazka**
## Description
This PR contains 3 commits, the first two are refactorings, the last one fixes
the issue.

----

In case the user had selected the external email client all email links would
not display any opt-in information (ticks). This is due to the ticks logic
being implemented in EmailUI which is only used in the sugar client case. The
external client path falls back to a simple mailto link.

This makes things always use EmailUI for rendering email links (including
ticks) and makes EmailUI use simple mailto links in case the user settings are
set to an external client.

## Motivation and Context

Fixes #6485

## How To Test This

Change the email client setting for the active user. The email links should always contain opt-in ticks.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Emails/EmailUI.php [hunk 1]
```diff
@@ -422,6 +422,24 @@ public function generateComposePackageForQuickCreateFromComposeUrl($emailLinkUrl
         return $this->generateComposePackageForQuickCreate($a_composeData, $emailLinkUrl, $lazyLoad);
     }
 
+    private function createEmailLink($module_name, $record_id, $name, $addr, $text) {
```
Comment (gymad) [inline modules/Emails/EmailUI.php]: Can you please add phpdoc above this PR to see the acceptable type of arguments and return value.

File: modules/Users/User.php [hunk 2]
```diff
@@ -1513,6 +1513,23 @@ public function getEmailLink2(
...
+                $focus->$emailField = $emailAddress;
+                $emailLink = $emailUI->populateComposeViewFields($focus, $emailField);
+                break;
+            }
+        }
+
+        return $emailLink;
+    }
+
+    public function getEmailClient() {
```
Comment (gymad) [inline modules/Users/User.php]: Can you please add phpdoc above this PR to see type of return value.

File: modules/Emails/EmailUI.php [hunk 3]
```diff
@@ -422,6 +422,24 @@ public function generateComposePackageForQuickCreateFromComposeUrl($emailLinkUrl
...
+        global $current_user;
```
Comment (gymad) [inline modules/Emails/EmailUI.php]: Using globals is never the right way. Pass it as an optional dependecy parameter and use it only if it's necessary.
(btw I like the way how you solve a tons of code duplication here :+1: )

File: modules/Emails/EmailUI.php [hunk 4]
```diff
@@ -422,6 +422,24 @@ public function generateComposePackageForQuickCreateFromComposeUrl($emailLinkUrl
...
+
+        if ($current_user->getEmailClient() == 'sugar') {
+            return '<a class="email-link"'
+                . ' onclick="$(document).openComposeViewModal(this);"'
+                . ' data-module="' . $module_name
+                . '" data-record-id="' . $record_id
+                . '" data-module-name="' . $name
+                . '" data-email-address="' . $addr  . '">'
+                . $text . '</a>';
+        } else {
```
Comment (gymad) [inline modules/Emails/EmailUI.php]: Using `else` is not necessary after a return statement (and I think it's bit confusing). Also it improves the code complexity. So I don't think it's needed here.

File: modules/Users/User.php [hunk 5]
```diff
@@ -1513,6 +1513,23 @@ public function getEmailLink2(
         $class = ''
     ) {
         $emailLink = '';
+
+        require_once('modules/Emails/EmailUI.php');
```
Comment (gymad) [inline modules/Users/User.php]: Can you please using `require_once` on top of the file. Also please use `__DIR__` constant as a prefix of file path to make sense where is the file exactly.

File: modules/Users/User.php [hunk 6]
```diff
@@ -1513,6 +1513,23 @@ public function getEmailLink2(
...
+        $emailUI = new EmailUI();
+        for ($i = 0; $i < count($focus->emailAddress->addresses); $i++) {
+            $emailField = 'email' . (string) ($i + 1);
+            $optOut = (bool)$focus->emailAddress->addresses[$i]['opt_out'];
```
Comment (gymad) [inline modules/Users/User.php]: I don't see the guarantee for existance of `'opt_out'` and `'email_address'` indexes. Can you please check if array indexes are exists before using it to evolve any additional and possible php error warning or notice in apache log. Use suitecrm log instead.

File: modules/Emails/EmailUI.php (hunk 3 above)
Comment (lazka) [reply modules/Emails/EmailUI.php]: Hm, I can only move it to the caller, use global there and then pass it 5 times, which seems worse to me. Any thoughts on this?

File: modules/Users/User.php (hunk 6 above)
Comment (lazka) [reply modules/Users/User.php]: I just changed the indent on this code (the gihub diff is a bit confusing imo), and I'd like to avoid unrelated changes in this PR. Should I look into this in a separate PR?

File: modules/Emails/EmailUI.php (hunk 3 above)
Comment (gymad) [reply modules/Emails/EmailUI.php]: Legacy code using global variables, I am just trying to avoid them as many places I can, doing this in a way like this:
```
public function doStuff(User $currentUser) {
  ...
}
```
(also I working in a wrapper class over the globals and superglobals - unfortunatelly not finished yet)

Of course, if it's not possible to avoid a global variable in a point I will approve it, I just would ask you to help me to avoid these global usages instead adding new if it's possible.
Btw, you'r right, ignore my previous comment.
Thank you

File: modules/Users/User.php (hunk 6 above)
Comment (lazka) [reply modules/Users/User.php]: > What do you mean "avoid unrelated changes"?

I mean that I tried to not change anything for the "sugar" client code path and I have not changed anything in this loop except removing the "if" surrounding it.

But I'll look into this.

File: modules/Emails/EmailUI.php (hunk 3 above)
Comment (lazka) [reply modules/Emails/EmailUI.php]: > Of course, if it's not possible to avoid a global variable in a point I will approve it, I just would ask you to help me to avoid these global usages instead adding new if it's possible.

Sounds good, I'll try to keep that in mind in the future :+1:

File: modules/Users/User.php (hunk 6 above)
Comment (gymad) [reply modules/Users/User.php]: Yeah, please try to keep the code behaviour as it is, your changes should be backward compatible as we don't want to brake anything else, even if caller function in someones custom folder.

**Comment by lazka** [comment]
(I've only rebased on top of hotfix, no changes)

File: modules/Users/User.php (hunk 6 above)
Comment (gymad) [reply modules/Users/User.php]: Could this function called from any custom modules?

Comment (lazka) [reply modules/Users/User.php]: Which function?

Maybe looking at the diff of the specific commit makes it clearer (the PR diff is confusing): https://github.com/salesagility/SuiteCRM/pull/6486/commits/001c85061d4f135cb9d9ab441b7b900bf42dc112

**Comment by Dillon-Brown** [comment]
Assessed
