### PR TITLE
Fixed #3655 - fix for popup compose view return message popup

### LINKED ISSUE #3655: SuiteCRM 7.9.0 - Sending email from Activity Subpanel error
#### Issue

When trying to send an email from Activity Subpanel -> Compose Email under the Case module, am getting a json error message printed on screen instead of js handling or showing error message in dialog box

#### Expected Behavior

Expect to have the email saved or send out. Even if any error should be display in dialog box

#### Actual Behavior

Email is sending out regardless if i send or save as draft. And error message appeal on screen instead of dialog box. A blank white screen printed with the error message in json format

#### Steps to Reproduce

1. Proceed to Case module
2. Click Compose Email under Activities subpanel
3. Input detail information and click on send/save as draft

#### Context

User are not able to reply email from the subpanel. I think this should be high in priority

#### Your Environment

* SuiteCRM Version used: 7.9.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Chrome 58.0.3029.110 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.6 & PHP 5.6.28
* Operating System and version (e.g Ubuntu 16.04): Windows 10 with MAMP running apache 2

email_issue

### PR DESCRIPTION
**Pull request by gymad**
## Description

fix for popup compose view return message popup

## Motivation and Context

see issue #3655 - SuiteCRM 7.9.0 - Sending email from Activity Subpanel error
also related to issue #3781 - Issue with return after sending an email

## How To Test This

see issue #3655:
Steps to Reproduce

Proceed to Case module
Click Compose Email under Activities subpanel
Input detail information and click on send/save as draft

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: jssource/src_files/include/javascript/EmailsComposeViewModal.js [hunk 1]
```diff
@@ -114,10 +114,10 @@
     self.emailComposeView = null;
```
Comment (daniel-samson) [inline jssource/src_files/include/javascript/EmailsComposeViewModal.js]: After testing your change I noticed tinymce editor is broken. We need to fix this as well as fixing the issue in the cases module.

screenshot_20170628_113353

Comment (gymad) [inline jssource/src_files/include/javascript/EmailsComposeViewModal.js]: This comment not related to the original issue about the incorrect JSON contents in responses.

**Comment by pgorod** [comment]
@gymad @daniel-samson while you're fixing the interaction between the compose window and the window below, it might be a good time to have a look at #3778. 

It's probably related, and I really think it shouldn't have been closed and moved to Trello as a mere suggestion. It's an email bug that causes people to lose work, so I'm sure we want it to be fixed in 7.9.2...
