### PR TITLE
Update sugar_3.js to fix a MassUpdate undefined error.

### LINKED ISSUE #7626: document.MassUpdate is undefined / Uncaught TypeError: Cannot read property 'uid' of undefined when going from list view to DetailView for Leads
#### Issue
The page slows down a ton and hundreds of errors get printed because of an undefined variable on the Leads page.

#### Expected Behavior
There would not be errors in my browser console.

#### Actual Behavior
There are hundreds of errors in my browser console and the page slows to a crawl.

#### Possible Fix
Not sure!

#### Steps to Reproduce
You can reproduce this on the demo site or on a locally hosted site running 7.10.x-hotfix, I'm not sure when it was introduced but it's been there at least since 7.10.18. I recommend using 7.10.x-hotfix if you can, since the location of the code has changed with some recent PRs (the PRs don't seem to have made any difference, however)

1. Go to Leads list view (you'll need to create a lead if you don't have any)
2. Open your browser console
3. Click on a Lead to open it.
4. Wait for the page to load
5. Look at the browser console and note dozens/hundreds of errors that say something about a TypeError and an undefined variable, and point to code in `sugar_grp1.js` (`sugar_3.js` in the actual source).

In Firefox the error is `TypeError: document.MassUpdate is undefined`, in Chrome it's `Uncaught TypeError: Cannot read property 'uid' of undefined`.

#### Context
This causes my browser to slow down to a crawl, it's practically unusable when I hit this bug.

#### Your Environment
* SuiteCRM Version used: 7.10.18, hotfix-7.10.x, and I was also able to reproduce it on the demo site, 7.11.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox 68.0
* Environment name and version (e.g. MySQL, PHP 7): MySQL 5.7, PHP 7.2
* Operating System and version (e.g Ubuntu 16.04): macOS Mojave (10.14.6)

### PR DESCRIPTION
**Pull request by connorshea**
## Description
Fix #7626 and #7244.

## Motivation and Context
It solves a JavaScript undefined variable error that could happen a few hundred times.

## How To Test This

- Pull down this branch
- Go to Leads list view (you'll need to create a lead if you don't have any)
- Open your browser console
- Click on a Lead to open it.
- Wait for the page to load
- Look at the browser console and make sure there aren't any errors that say something about a TypeError and an undefined variable, and point to code in `sugar_grp1.js` (`sugar_3.js` in the actual source).

Essentially, try to reproduce #7626 and make sure you're unable to.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by connorshea** [comment]
I think the code coverage job timed out :(

File: jssource/src_files/include/javascript/sugar_3.js [hunk 1]
```diff
@@ -2028,11 +2028,13 @@ sugarListView.get_num_selected_string = function () {
  * @returns {number}
  */
 sugarListView.get_num_selected = function () {
-  var the_form = document.MassUpdate;
-  if (typeof the_form != 'undefined' && the_form.select_entire_list.value == 1) {
-    var selectCount = $("input[name='selectCount[]']:first");
-    if (selectCount.length > 0)
-      return parseInt(selectCount.val().replace("+", ""));
+  if (document.MassUpdate != 'undefined') {
```
Comment (lazka) [inline jssource/src_files/include/javascript/sugar_3.js]: Hm, in which case should "document.MassUpdate" be 'undefined'? Isn't this just skipping get_checks_count in call cases?

Comment (mrbarletta) [reply jssource/src_files/include/javascript/sugar_3.js]: In my scenario, (7.8.x instance upgraded to 7.10.x) once I click on a listview item I get the same error in the detail view (hundreds of times)

Comment (connorshea) [reply jssource/src_files/include/javascript/sugar_3.js]: Based on when the error occurs, it should be defined when on a page where you can actually use the mass update functionality, but then when you switch to another page via ajax that doesn't have that, it becomes undefined. I'm not entirely sure why the code stays around at all, but 🤷‍♂ I don't think it should break anything, and if you want to test it I'd be happy to have the functionality validated :)

Comment (lazka) [reply jssource/src_files/include/javascript/sugar_3.js]: You are never checking if it is undefined, you are comparing it against a string "undefined".

Comment (connorshea) [reply jssource/src_files/include/javascript/sugar_3.js]: 🤦‍♂ oops, I've updated it to compare with the type now.

**Comment by connorshea** [comment]
Rebased to fix the merge conflict in the minified file >.>

File: jssource/src_files/include/javascript/sugar_3.js [hunk 2]
```diff
@@ -2028,11 +2028,13 @@ sugarListView.get_num_selected_string = function () {
  * @returns {number}
  */
 sugarListView.get_num_selected = function () {
-  var the_form = document.MassUpdate;
-  if (typeof the_form != 'undefined' && the_form.select_entire_list.value == 1) {
-    var selectCount = $("input[name='selectCount[]']:first");
-    if (selectCount.length > 0)
-      return parseInt(selectCount.val().replace("+", ""));
+  if (typeof document.MassUpdate != 'undefined') {
```
Comment (lazka) [inline jssource/src_files/include/javascript/sugar_3.js]: (This change doesn't change anything now)

**Comment by connorshea** [comment]
@Mac-Rae Ready to be reviewed again :)

**Comment by cameronblaikie** [comment]
Assessed :+1:
