### PR TITLE
Fix #10199 - PHP Fatal error: Uncaught Error: Non-static method Sug…

### LINKED ISSUE #10199: PHP Fatal error:  Uncaught Error: Non-static method SugarWidgetReportField::_get_column_select()
There seem to be a mismatch of static non static functions in the SugarwidgetFields.
Most of the times it is called non-static like $this->_get_column_select() , but here in this widget id is called statically.
Also it is overwritten in the class , but in some places the parent::_get_column_select seems to be called.
I don't know twht causes this, as I did not hear of anyone if this makes problems.

#### Issue
Following in PHP log:
```
[Thu Sep 21 16:39:35.319406 2023] [proxy_fcgi:error] [pid 3649778:tid 140631512569600] [remote 10.207.24.9:50374] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Non-static method SugarWidgetReportField::_get_column_select() cannot be called statically in /var/www/suite/include/generic/SugarWidgets/SugarWidgetFieldname.php:231
Stack trace:
#0 /var/www/suite/include/Dashlets/DashletGeneric.php(365): SugarWidgetFieldName->queryFilterone_of()
#1 /var/www/suite/include/Dashlets/DashletGeneric.php(416): DashletGeneric->buildWhere()
#2 /var/www/suite/modules/Home/index.php(244): DashletGeneric->process()
#3 /var/www/suite/modules/Home/views/view.list.php(55): include('...')
#4 /var/www/suite/include/MVC/View/SugarView.php(210): HomeViewList->display()
#5 /var/www/suite/include/MVC/Controller/SugarController.php(432): SugarView->process()
#6 /var/www/suite/include/MVC/Controller/SugarController.php(363): SugarController->processView()
#7 /var/www/suite/include/MVC/SugarApplication.php(101): SugarController->execute()
#8 /var/www/suite/index.php(52): SugarApplication->execute()
#9 {main}
  thrown in /var/www/suite/inc...'
```

#### Expected Behavior
No fatal PHP errors

#### Actual Behavior
Fatal PHP errors

#### Your Environment

* SuiteCRM Version used: 7.14.0
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7): PHP 8.2.10
* Operating System and version (e.g Ubuntu 16.04): Debian GNU/Linux 11

### PR DESCRIPTION
**Pull request by TwizzX17**
…arWidgetReportField::_get_column_select()

PHP version 8 seems to have deprecated the non-static method calling. In this fix the class SugarWidgetFieldid is being instantiated and set as a property for reusability throughout the class.

## Description

Solving this issue: #10199

## How To Test This

The bug occurs when having a widget on your dashboard (e.g. "My Top Open Opportunities : Options") and adding the following filter: disable "only my items" checkbox and add a "assigned To". This will cause the dashboard to crash.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by serhiisamko091184** [comment]
Hello @TwizzX17 ,
thanks for your contribution, 
would you please: 

1) combine your commits into one; 
2) slightly change message text - Fix in stead Fixed.
image

As example: 
https://github.com/salesagility/SuiteCRM/pull/10122

Thanks a lot in advance. 

Regards,
Serhii

**Comment by TwizzX17** [comment]
Hi @serhiisamko091184,
I've made the changes you've mentioned.
Best regards
TwizzX

**Comment by serhiisamko091184** [comment]
Hello @TwizzX17 ,
thanks a lot for quick reply and changes! 

Regards,
Serhii

File: include/generic/SugarWidgets/SugarWidgetFieldname.php [hunk 1]
```diff
@@ -55,6 +55,7 @@ public function __construct(&$layout_manager)
     {
         parent::__construct($layout_manager);
         $this->reporter = $this->layout_manager->getAttribute('reporter');
+        $this->sugarWidgetFieldId = new SugarWidgetFieldId($layout_manager);
```
Comment (clemente-raposo) [inline include/generic/SugarWidgets/SugarWidgetFieldname.php:58]: Hi @TwizzX17, 

Thank you for your PR.

@TwizzX17 @serhiisamko091184 

The `sugarWidgetFieldId` is not declared on the class. It should be declared, otherwise we can get warnings/notices.

Comment (TwizzX17) [reply include/generic/SugarWidgets/SugarWidgetFieldname.php:59]: Hi @clemente-raposo,
Of course - I've declared the property as a protected property. Do you agree with the implementation?

**Review by clemente-raposo — APPROVED** [review]

**Review by johnM2401 — APPROVED** [review]
