### PR TITLE
Fix #4231 Stop appending duplicated viewdefs

### LINKED ISSUE #4231: Module Layout: "Tabs" showing as "Panels"
#### Issue
New sections created within a module layout are only shown as panels. Changing the Display Type to "Tab" does not have any effect.

#### Expected Behavior
Layout section showing as Tab.

#### Actual Behavior
Layout section showing as Panel.

#### Steps to Reproduce
As example we go with the account layout
1. open Admin > Studio > Accounts > Layouts > EditView
1.1 select "Sync with deteailed view"
2. add a new Panel (Section) from the Toolbox
3. give the Panel a name (it is not possible to select the Display Type yet)
4. add a field to the Panel
5. click on save and deploy
6. now we change the Display Type of the created Panel (Section) to "Tab"
7. click on saven and deploy
8. Check the layout in the detailed view 

#### Context
medium priority

#### Your Environment
* SuiteCRM Version used: 7.9.5
* Browser name and version: Edge, Chrome, Firefox
* Environment name and Version: MariaDB, php 7
* Operating System and version: Debian 9.1

### PR DESCRIPTION
**Pull request by PedroErnst**
Fixed a possible bug introduced in 680896d4d6b16ca46ebfde21051b23b99de1f3bf which overwrites changes made in Studio.

## Motivation and Context

Issue #4231 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

**Comment by pgorod** [comment]
Hi @PedroErnst, is this still "work in progress"? Should we ask the guys on the issue page to test it already?

**Comment by PedroErnst** [comment]
Yes, good to go for testing!

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php [hunk 1]
```diff
@@ -344,16 +344,6 @@ protected function _saveToFile($filename, $defs, $useVariables = true, $forPopup
 
         $out .= ";\n";
 
-        if(!empty($this->_originalViewTemplateDefs)) {
```
Comment (daniel-samson) [inline modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: The listviewdefs.php depends on this code. In 7.9, I added a means to customise the templateMeta in the list view, in the same way you can in the edit / detail view. So that you can include javascript, and customise the bulk action button, and add your own custom buttons.

When you save a list view layout in studio this will cause the list view buttons to disappear. For example the list view in the emails module.

See #3496 for details.

So ... We need to find an other way to solve this issue.

Comment (PedroErnst) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: Ok I think this will do. In the case of the listview the structure of the defs is very different and does not contain an array index with the name of the view.

Comment (PedroErnst) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: @daniel-samson please review these changes

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php [hunk 2]
```diff
@@ -353,12 +353,27 @@ protected function _saveToFile($filename, $defs, $useVariables = true, $forPopup
...
         if (sugar_file_put_contents($filename, $out) === false) {
             $GLOBALS ['log']->fatal(get_class($this) . ": could not write new viewdef file " . $filename);
         }
     }
 
+    /**
+     * @param $defs The definitions to save
+     * @return bool
+     */
+    private function shouldAppendOriginalViewTemplateDefs($defs)
```
Comment (zoltankocsardi) [inline modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: Please, rename this function. It sounds like a method for testing purposes. Since it returns boolean, maybe you can use 'is' prefix.

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php [hunk 3]
```diff
@@ -353,12 +353,27 @@ protected function _saveToFile($filename, $defs, $useVariables = true, $forPopup
...
+    {
+        if (empty($this->_originalViewTemplateDefs)) {
+            return false;
+        }
+        if (is_array($defs) && isset($defs[$this->_viewName])) {
+            // The defs are already being saved we don't want to duplicate them
+            return false;
+        }
```
Comment (zoltankocsardi) [inline modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: You are able to merge these conditions.

Comment (PedroErnst) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: True, but I think it's more readable like this.

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php (hunk 1 above)
Comment (daniel-samson) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: Just test your new changes it seems to work

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php (hunk 2 above)
Comment (PedroErnst) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: Ok done!

File: modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php (hunk 3 above)
Comment (zoltankocsardi) [reply modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php]: :D
