### PR TITLE
fixed #6050 No submit button while editing imported email

### LINKED ISSUE #6050: No submit button on editing imported email
After importing an email, it's impossible to edit the import options (assigned to, related to) because there is no OK button to submit changes.

#### Issue
When importing an email, a modal window appears in order to fill up _assigned-to_ and _related-to_ fields. This modal window has an _OK_ and a _Cancel_ button. It works fine!

After importing, the option Edit shows the same form, but not in a modal window and without any OK or Cancel button or any other way to submit changes. Any modification made in this page **will not be saved**, making it impossible to change the assignment or relation of an email if it was already imported.

#### Expected Behavior
Show an OK and Cancel button.

#### Actual Behavior
No OK button. No Cancel button. No any other way to submit changes. 

#### Steps to Reproduce
1. Go to Emails module
2. Pick an email
3. Click Actions -> Import
4. Assign or relate to any user/contact/account
5. Click Actions -> Edit

#### Context
In our use case, many times the assignments for a message will change depending on the level of the conversation. Changing the user assigned to an email is fundamental for our way of using the CRM. For us, this is high priority.

#### Your Environment
* SuiteCRM Version used: 7.10.7
* Browser: Google Chrome Versión 67.0.3396.87 (Build oficial) (64 bits)
* Environment: PHP 7.0 FPM, Percona Server 5.6, Apache 2
* Operating System: Ubuntu 17.10

### PR DESCRIPTION
**Pull request by code-ph0y**
fix for #6050 - No submit button while editing imported email

## Description
Fix will use the correct folder for import.

## Motivation and Context
To resolve the issue listed in #6050 

## How To Test This
1. Set up group email account
2. Import a selected email
3. Set up a personal email account
4. Import a selected email
5. Switch the folders and see that the imported emails flag is changing and also the listed issue is fixed

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/Emails/include/ListView/ListViewDataEmails.php [hunk 1]
```diff
@@ -549,20 +549,20 @@ protected function getEmailRecordFieldValue($field, $emailHeader, $inboundEmail,
                 $importedEmailBeans = BeanFactory::getBean('Emails');
                 $is_imported = $importedEmailBeans->get_full_list(
                     '',
-                    'emails.uid LIKE "' . $uid . '"'
+                    'emails.uid LIKE "' . $uid . '" AND emails.mailbox_id = "' . $inboundEmail->id . '"'
```
Comment (gymad) [inline modules/Emails/include/ListView/ListViewDataEmails.php]: Please use quote() or quoted() method of DBManager before concat into a query string.

File: modules/Emails/EmailsController.php [hunk 2]
```diff
@@ -636,11 +636,14 @@ public function action_DisplayDetailView()
...
-        $inboundEmailRecordIdQuoted = $db->quote($_REQUEST['inbound_email_record']);
-        $uidQuoted = $db->quote($_REQUEST['uid']);
-        
-        $result = $emails->get_full_list('', "mailbox_id = '" . $inboundEmailRecordIdQuoted . "' AND uid = '" . $uidQuoted . "'");
+
+        $inboundEmailRecordId = $_REQUEST['inbound_email_record'];
+
+        $uid = $_REQUEST['uid'];
+
+        $subQuery = "`mailbox_id` = " . $db->quoted($inboundEmailRecordId) . " AND `uid` = " . $db->quoted($uid);
```
Comment (gymad) [inline modules/Emails/EmailsController.php]: I'm sorry I couldn't notice it earlier but I just want to let you know you can use `SuiteValidator::isValidId()` for any suitecrm id validation before using it. This validation result also implicate that if you can using it as a valid ID in a query before requesting the sql server to resolve the queries in these areas (invalid ID obiously will failing so we don't have to waiting for the mysql server responses). It could improve the performance too.

**Comment by cameronblaikie** [comment]
Assessed :+1:
