### PR TITLE
Fixed #6025 - Fix for issue #6025 - Newsletter campaign target list selection broken

### LINKED ISSUE #6025: Choose Targets Campaigns error last step
#### Steps to Reproduce

The error is when you create a **Newsletter campaign** with both version 7.10.5 and 7.10.6

1. **Launch wizard** -> step **Target Lists** -> select **Target**
2. Next step **Templates**, back to step previous, loses the target list and appears in the list of new target lists that I have not created.
3.  In the step **Send Email and Summary**, as it loses the target lists, Choose Targets with red blade 

screenshot_0
screenshot_2
screenshot_3
screenshot_5
screenshot_6
screenshot_7

#### Context

**suiteCRM forum**
[TOPIC: Choose Targets Campaigns error last step](https://suitecrm.com/suitecrm/forum/gestion-de-errores/19478-choose-targets-campaigns-error-last-step#67586)

I tried it in the official demo with Newsletter type.

It is clearly a bug as you highlighted.

1. If you navigate back no target list remains selected.
2. However if you exit from the creation of the Campaign and go to the list view, then select the campaign, in Edit view all available target lists are selected.

This a very dangerous and nasty bug, high priority

This is a **critical issue** because if one does't realise the problem he may end up sending a newsletter to all atrget lists created in the system and this is really unwanted and against **GDPR**

#### Your Environment

* SuiteCRM Version used: 7.10.5 and 7.10.6
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): all browsers
* Environment name and version (e.g. MySQL, PHP 7): Mysql an php7
* Operating System and version (e.g Ubuntu 16.04): Centos

### PR DESCRIPTION
**Pull request by gymad**
## Description

Provide a fix for issue #6025 - Newsletter campaign target list selection broken

## Motivation and Context

Target list selection should works

## How To Test This

see everything in the related issue above

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: tests/acceptance/modules/TargetLists/TargetListsCest.php [hunk 1]
```diff
@@ -30,15 +30,15 @@ public function _before(AcceptanceTester $I)
...
-     * @param \Step\Acceptance\Targets $targets
+     * @param \Step\Acceptance\TargetList $targetList
      * @param \Helper\WebDriverHelper $webDriverHelper
      *
      * As an administrator I want to view the targets module.
      */
     public function testScenarioViewTargetsModule(
         \AcceptanceTester $I,
         \Step\Acceptance\ListView $listView,
-        \Step\Acceptance\Targets $targets,
```
Comment (samus-aran) [inline tests/acceptance/modules/TargetLists/TargetListsCest.php]: Does this mean we don't have Acceptance Test for Targets or was this a mistake originally and giving us a false positive?

Comment (Dillon-Brown) [reply tests/acceptance/modules/TargetLists/TargetListsCest.php]: Yes, the ViewTargetModule test was previously looking at the "Targets" module instead of "Targets - List".

**Comment by samus-aran** [comment]
Code Looks good +1

**Comment by Dillon-Brown** [comment]
Assessed
