### PR TITLE
Fixed #6303 - Administration / System Settings / ERROR in log: argument cache/themes/SuiteP/modules is not a file or a dir.

### LINKED ISSUE #6303: Administration / System Settings / ERROR in log: argument cache/themes/SuiteP/modules is not a file or a dir.
#### Issue

Suitecrm.log shows the error below whenever I click **_Adminstration / System Settings / Save_**

I can't verify this error in the demo site, as I would need Administrator access (and I don't have that).

This error is occurring in version 7.10.7

```
Tue Sep 11 14:53:12 2018 [1428][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
```

This error occurs even if I don't change any values in System Settings.  

I have checked and re-checked file permissions.  Including running the "installation wizard - step 1" which checks all file permissions (and the checks passed).

#### Expected Behavior
I don't expect to see an error on save.  I don't know what happens (downstream) from this error when it occurs.  

#### Possible Fix
I don't have a possible fix.

#### Steps to Reproduce

1.  I reproduced error this with a fresh clean install of 7.10.7
2. Click Administration
3. Click System Settings
4. Click Save <- just clicking SAVE produces the error - you don't even have to change anything.

This error is also created when I performed a "Quick Repair and Rebuild".

#### Context
I don't know the priority of this error, as I don't know if it is not saving some things and not others.  I do know it is recorded as a FATAL error.

#### Your Environment
* SuiteCRM Version used: 7.10.7 - fresh, clean, install. 
* Browser name and version: Chrome | 69.0.3497.81 (Official Build) (64-bit)
* Environment name and version MySQL, PHP 7.0
* Operating System and version: Linux footprint 4.4.126-0.ksplice-lts-generic #2 SMP Tue Apr 10 12:33:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Checks that a directory exists before attempting to remove it. This fixes:

```
Tue Sep 11 14:53:12 2018 [1428][1][FATAL] ERROR: rmdir_recursive(): argument cache/themes/SuiteP/modules is not a file or a dir.
``` 

## Motivation and Context

Issue reference: #6303 

## How To Test This

1. Go into system settings.
2. Click on save and check the suitecrm.log.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: include/SugarTheme/SugarTheme.php [hunk 1]
```diff
@@ -393,8 +393,8 @@ public function __destruct()
                 unlink("$cachedir/spriteCache.php");
             }
 
-            if (strlen($cachedir)>1) {
-                rmdir_recursive($cachedir.'/modules');
+            if (($cachedir) && is_dir($cachedir . '/modules') && (!rmdir_recursive($cachedir . '/modules'))) {
```
Comment (gymad) [inline include/SugarTheme/SugarTheme.php]: So many extra brackets..
