### PR TITLE
FIX #7250 - Remove PHP Notices in include/ListView/ListViewSmarty.php

### LINKED ISSUE #7250: Notices in ListViews
#### Issue

If you do not set up the key `"width"` in `listviewdefs.php`, some PHP Notices are shown:

```
( ! ) Notice: Undefined index: width in /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSmarty.php on line 136
--
1 | 0.0001 | 246456 | {main}(  ) | .../index.php:0
2 | 0.0373 | 10473216 | SugarApplication->execute(  ) | .../index.php:80
3 | 0.0621 | 14100208 | CustomSugarController->execute(  ) | .../SugarApplication.php:113
4 | 0.0682 | 14307504 | CustomSugarController->processView(  ) | .../SugarController.php:267
5 | 0.0693 | 14609640 | CustomSugarView->process(  ) | .../SugarController.php:318
6 | 0.1248 | 15758552 | gcoop_carterasViewList->display(  ) | .../SugarView.php:108
7 | 0.1248 | 15758648 | ViewList->display(  ) | .../view.list.php:26
8 | 0.2455 | 16080192 | gcoop_carterasViewList->listViewProcess(  ) | .../view.list.php:356
9 | 0.2725 | 16570984 | ListViewDisplay->setup(  ) | .../view.list.php:484
10 | 0.2921 | 17591712 | ListViewSmarty->process(  ) | .../ListViewDisplay.php:188



( ! ) Notice: Undefined index: width in /home/jose/trabajos/gca-suitecrm7.10x/include/ListView/ListViewSmarty.php on line 143
--
1 | 0.0001 | 246456 | {main}(  ) | .../index.php:0
2 | 0.0850 | 10464144 | SugarApplication->execute(  ) | .../index.php:80
3 | 0.1052 | 14090984 | CustomSugarController->execute(  ) | .../SugarApplication.php:113
4 | 0.1101 | 14298344 | CustomSugarController->processView(  ) | .../SugarController.php:267
5 | 0.1131 | 14604608 | CustomSugarView->process(  ) | .../SugarController.php:318
6 | 0.1639 | 15753536 | gcoop_carterasViewList->display(  ) | .../SugarView.php:108
7 | 0.1639 | 15753632 | ViewList->display(  ) | .../view.list.php:26
8 | 0.2696 | 16069672 | gcoop_carterasViewList->listViewProcess(  ) | .../view.list.php:356
9 | 0.2912 | 16559776 | ListViewDisplay->setup(  ) | .../view.list.php:484
10 | 0.3088 | 17586704 | ListViewSmarty->process(  ) | .../ListViewDisplay.php:188
```

#### Expected Behavior

Handle the absence of that key in `include/ListView/ListViewSmarty.php`

#### Possible Fix

Replace the following lines in `include/ListView/ListViewSmarty.php`

```php
         foreach ((array)$this->displayColumns as $name => $params) {
             $totalWidth += (int)$params['width'];
         }
        $adjustment = $totalWidth / 100;

        $contextMenuObjectsTypes = array();
        foreach ((array)$this->displayColumns as $name => $params) {
            $this->displayColumns[$name]['width'] = floor(((int)$this->displayColumns[$name]['width']) / $adjustment);
            // figure out which contextMenu objectsTypes are required
            if (!empty($params['contextMenu']['objectType'])) {
                $contextMenuObjectsTypes[$params['contextMenu']['objectType']] = true;
            }
        }
```

for this:

```php
        foreach ((array)$this->displayColumns as $name => $params) {
            $p = (isset($params['width']))? (int)$params['width'] : 0;
            $totalWidth += $p;
        }
        $adjustment = $totalWidth / 100;

        $contextMenuObjectsTypes = array();
        foreach ((array)$this->displayColumns as $name => $params) {
            if (!isset($this->displayColumns[$name]['width'])) {
                $this->displayColumns[$name]['width'] = 0;
            }
            $this->displayColumns[$name]['width'] = floor(((int)$this->displayColumns[$name]['width']) / $adjustment);
            // figure out which contextMenu objectsTypes are required
            if (!empty($params['contextMenu']['objectType'])) {
                $contextMenuObjectsTypes[$params['contextMenu']['objectType']] = true;
            }
        }
```

#### Steps to Reproduce

1. Remove 'width' key in listviewdefs.php
2. Verify Notices in PHP log

#### Your Environment

* SuiteCRM Version used: 7.10.x

### PR DESCRIPTION
**Pull request by Abuelodelanada**
## Description

Refer to #7250

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: include/ListView/ListViewSmarty.php [hunk 1]
```diff
@@ -133,12 +133,15 @@ public function process($file, $data, $htmlpublic)
 
         $totalWidth = 0;
         foreach ((array)$this->displayColumns as $name => $params) {
-            $totalWidth += (int)$params['width'];
+            $totalWidth += (isset($params['width']))? (int)$params['width'] : 0;
```
Comment (Dillon-Brown) [inline include/ListView/ListViewSmarty.php]: Unnecessary parenthesis can be removed:

```suggestion
            $totalWidth += isset($params['width']) ? (int)$params['width'] : 0;
```

Comment (Abuelodelanada) [reply include/ListView/ListViewSmarty.php]: Fixed in https://github.com/salesagility/SuiteCRM/pull/7251/commits/502f9726b7cad005c7b0e2439d26273228484cfa

**Comment by cameronblaikie** [comment]
Assessed :+1:
