### PR TITLE
FIXED #3756 - Popup Studio and Calendar don't auto-close

### LINKED ISSUE #3756: Popup Studio and Calendar don't auto-close
#### Issue

When saving chaned labels in Studio, or when hovering over an event in the Calendar, a popup appears. This popup doesn't automatically disappear when expected.

#### Expected Behavior

Especially for Calendar events, I expect these popups to auto close when not hovering over the event anymore.

In Studio, this messages you get when saving changed labels, for example, used to be a message at the top of the screen that automatically disappear after a certain amount of time. Also, the screen isn't blocked, so you can continue working, so the work flow isn't interrupted.

#### Actual Behavior

Calendar event popups need a manual click on the close button to close.
Studio popups need a manual click on the close button to close, blocking the screen and all functions until you do so.

#### Steps to Reproduce

Calendar popups:

1. Create an event that appears on the Calendar
2. Go to the Calendar and hover over this event

Studio popups

1. Go to Labels of a module
2. Make a change and click save

#### Your Environment

* SuiteCRM Version used: 7.8.1 + SuiteP
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Firefox & Chrome
* Environment name and version (e.g. MySQL, PHP 7): Php 5.6 & 7.0
* Operating System and version (e.g Ubuntu 16.04): Centos 7

### PR DESCRIPTION
**Pull request by cameronblaikie**
When saving chaned labels in Studio, or when hovering over an event in the Calendar, a popup appears. This popup doesn't automatically disappear when expected.

## Motivation and Context

https://github.com/salesagility/SuiteCRM/issues/3756
## How To Test This

Studio popups

1. Go to Labels of a module.
2. Make a change and click save.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/ModuleBuilder/javascript/ModuleBuilder.js [hunk 1]
```diff
@@ -658,10 +658,13 @@ if (typeof('console') == 'undefined') {
               title: SUGAR.language.get('ModuleBuilder', 'LBL_AJAX_RESPONSE_TITLE'),
               msg: SUGAR.language.get('ModuleBuilder', 'LBL_AJAX_RESPONSE_MESSAGE'),
               width: 500,
-              close: true
+              close: true,
+
             });
             ModuleBuilder.updateContent(o);
-          }
+            setTimeout(YAHOO.SUGAR.MessageBox.hide, 3000)
```
Comment (Dillon-Brown) [inline modules/ModuleBuilder/javascript/ModuleBuilder.js]: Unterminated statement

**Comment by willrennie** [comment]
Assessed :+1:

**Comment by connorshea** [comment]
This PR seems to have caused flaky test failures, the module builder tests rely on the behavior of the popups not closing themselves. For some reason, the tests aren't able to consistently close the popup before this timeout is hit and the popup closes itself.

I've opened #7532 to try and fix this. Unfortunately, it has the downside of making the tests take longer since it tries to wait until the modal closes itself before doing anything (waiting for the text to show up and then clicking the closing button is inconsistent, so it's not a good alternative).

Any other ideas are welcome :)
