### PR TITLE
Fixed #6131 - Issue with DetailView of Email module on 7.10.7 xampp

### LINKED ISSUE #6131: Issue with DetailView of Email module on 7.10.7 xampp
DetailView of email module shows the raw php code on Xampp on windows 

#### Issue
Since upgrading... detailview of an email is broken on xampp using windows (have not tested on linux)

#### Expected Behavior
When clicking into the detailview of an email... the email content should display

#### Actual Behavior
The raw php code is displayed.

#### Possible Fix
I fixed by reverting change made on modules/emails/vardefs.php with commit a60c60f1 and running quick repair

#### Steps to Reproduce
Upgrade on windows xampp to v 7.10.7 from previous version and go to detailview of any outbound or inbound email

#### Your Environment
Suite: 7.10.7 upgrade from 7.10.6
Windows 10 XAMPP PHP 7

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Fixed an issue with the email detailview not displaying the correct view when using xampp and instead outputting raw PHP code.

## Motivation and Context

Issue reference: #6131 

## How To Test This

1. Repair and rebuild
2. See if the email module detail-view displays correctly.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: include/SugarFields/Fields/EmailBody/SugarFieldEmailBody.php [hunk 1]
```diff
@@ -64,4 +64,55 @@ public function getDetailViewSmarty($parentFieldArray, $vardef, $displayParams,
...
+    {
+        if (empty($vardef['value'])) {
+            if (!empty($vardef['default'])) {
+                return $vardef['default'];
+            } elseif (!empty($vardef['default_value'])) {
+                return $vardef['default_value'];
+            }
+        }
+
+        return utf8_decode($vardef['value']);
```
Comment (gymad) [inline include/SugarFields/Fields/EmailBody/SugarFieldEmailBody.php]: Please check and handle the case when `$vardef['value']` and/or default/default_value is not set. For e.g what happening if a $vardef has non of these: 
`if (!isset($vardef['value']) && !isset($vardef['default']) && !isset($vardef['default_value'])) ... //??`

**Comment by jamiemurray** [comment]
I can confirm this resolves the issue.

**Comment by samus-aran** [comment]
Thanks @jamiemurray for testing - @Dillon-Brown Is just triple checking on his side that he feels comfortable that this works :+1:
