### PR TITLE
Fixed #3522 - Custom files not overriding SuiteP core - 7.9 Beta

### LINKED ISSUE #3522: Custom files not overriding SuiteP core - 7.9 Beta
#### Issue

I wanted to override some language strings as well as some tpls in SuiteP.

I edited the login.tpl and en_us.lang.php files and placed the tpls in /custom/themes/SuiteP/tpls/ and the lang file in /custom/languages/

I then did a quick repair which did not do anything as the old strings were still showing. I also did a rebuild javascript languages which also had no effect.

I also edited the footer.tpl and placed it in the custom folder, which DID work, a custom style.css also worked fine.

#### Expected Behavior

Placing tpl and and lang files in the custom folder did not override the core SuiteP files.

#### Actual Behavior

Old string values remain.

#### Steps to Reproduce

1. Edit a tpl listed above or a lang file and place it in the appropriate custom folder.
2. Run a quick repair

#### Your Environment

* SuiteCRM Version used: 7.9 Beta
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): 57.0.2987.133 (64-bit)
* Environment name and version (e.g. MySQL, PHP 7): MySQL, PHP 5.5.9
* Operating System and version (e.g Ubuntu 16.04): OSX

### PR DESCRIPTION
**Pull request by Dillon-Brown**
## Description

Changed modules/Users/Login.php to check custom versions of login.tpl. This fixes placing tpl files in the custom folder not overriding the core SuiteP files.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [X] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [X] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/Users/Login.php [hunk 1]
```diff
@@ -203,25 +205,28 @@ function validateAndSubmit(){
...
 } elseif (file_exists('custom/modules/Users/login.tpl')) {
-	echo $sugar_smarty->display('custom/modules/Users/login.tpl');
+    echo $sugar_smarty->display('custom/modules/Users/login.tpl');
+} elseif (file_exists('themes/' . SugarThemeRegistry::current() . '/login.tpl')) {
+    echo $sugar_smarty->display('themes/' . SugarThemeRegistry::current() . '/login.tpl');
+} elseif (file_exists('modules/Users/login.tpl')) {
+    echo $sugar_smarty->display('modules/Users/login.tpl');
 } else {
-	echo $sugar_smarty->display('modules/Users/login.tpl');
+    $GLOBALS['log']->fatal('login.tpl not found');
```
Comment (daniel-samson) [inline modules/Users/Login.php]: To ensure that this gets picked up by the developer. You should throw an exception with the same message. This will then be output to the suitecrm.log and to the apache error log but with a stack trace.

Example:
`throw new Exception('login.tpl not found');`

To ensure that the user is aware that an error has occured. You should add a label into include/language/en_us.lang.php and echo the label out to the page

Example:
`echo <span class="error="> $app_strings['LBL_MISSING_TEMPLATE']</span>`
