### PR TITLE
Fix #2221 - Restrict Reports based on Target Module

### LINKED ISSUE #2221: Restrict Reports based on Target Module
Users are see the results for reports on modules they do not have access to.
#### Issue

If a user has access to AOR Reports, then they are capable of seeing the results of all reports. This extends to reports that target modules that the user might not have read access for, so they are able to see the results for these reports and even edit them (if they have edit privileges for AOR Reports). Users should not be able to see data on modules they do not have read access for or create reports to get that data.
#### Expected Behavior

Users should not be able to access reports about modules they don't have access to.
#### Actual Behavior

Users can see the results of reports that target modules they don't have access to and edit these reports.
#### Steps to Reproduce

1. Login as a user with no permissions to a module (Accounts etc).
2. Navigate to Reports and open/create a report on the restricted module.
#### Your Environment

- SuiteCRM Version used:
- Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
- Environment name and version (e.g. MySQL, PHP 7):
- Operating System and version (e.g Ubuntu 16.04):

### PR DESCRIPTION
**Pull request by MikeyJC**
## Description

AOR Reports now restricts the results and ability to edit/create reports that target modules the user does not have read access to. If they open a report that targets a module they don't have access to then the query is not built and the results return nothing. They also don't have access to the edit/duplicate/delete buttons for these reports. If they are creating a report and try to the select a module they don't have access to, the field tree returns no results. 

relates #2221 
## Motivation and Context

If users have permission to view reports, then they are able to retrieve data on modules they otherwise do not have access to. This change would alleviate that.
## How To Test This

1. Login as a user that has read access restrictions on a module (e.g. Accounts).
2. Navigate to Reports and test opening/creating reports that target the restricted module.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
### Final checklist

- [x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ ] My change requires a change to the documentation.
- [ ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.

### CODE REVIEW

File: modules/AOW_WorkFlow/aow_utils.php [hunk 1]
```diff
@@ -34,14 +34,16 @@ function getModuleFields($module, $view='EditView',$value = '', $valid = array()
...
             foreach($mod->field_defs as $name => $arr){
-                if($arr['type'] != 'link' &&((!isset($arr['source']) || $arr['source'] != 'non-db') || ($arr['type'] == 'relate' && isset($arr['id_name']))) && (empty($valid) || in_array($arr['type'], $valid)) && $name != 'currency_name' && $name != 'currency_symbol'){
-                    if(isset($arr['vname']) && $arr['vname'] != ''){
-                        $fields[$name] = rtrim(translate($arr['vname'],$mod->module_dir), ':');
-                    } else {
-                        $fields[$name] = $name;
-                    }
-                    if($arr['type'] == 'relate' && isset($arr['id_name']) && $arr['id_name'] != ''){
-                        $unset[] = $arr['id_name'];
+                if(ACLController::checkAccess($mod->module_dir, 'list', true)) {
```
Comment (samus-aran) [inline modules/AOW_WorkFlow/aow_utils.php]: Assuming this was included for a related reason for reports?

**Comment by samus-aran** [comment]
Hey @MikeyJC Please review the comment I mention.
