### PR TITLE
Fixed #8366 - V8 API Filtering W/ OR Operator Chained Conditions

### LINKED ISSUE #8366: V8 API Filtering W/ OR Operator Chained Conditions
#### Issue

When filtering on an API GET modules endpoint, using the `AND` operator to chain conditions appears to work fine with the below basic example. However, using the `OR` operator results in no filters being applied from what I can tell as all records are returned regardless of whether they match the criteria. 

Working `AND` example:
```
/V8/module/Accounts?filter[name][eq]=Test&filter[operator]=and&filter[account_type][eq]=Customer
```

Broken `OR` example:
```
/V8/module/Accounts?filter[name][eq]=Test&filter[operator]=or&filter[account_type][eq]=Customer
```

#### Expected Behavior

Only records matching the filter criteria should be returned and not the full list.

#### Actual Behavior

All filters are ignored and the full list is returned.

#### Possible Fix

Debug endpoint, identify where the filters are either overwritten or dropped and implement a fix.  

#### Steps to Reproduce

1. Create an Account record that matches the filter criteria outlined above.
2. Create a one or more Account records that does not match the criteria.
3. Apply the above outlined filters to the GET modules API call, targeting Accounts.
4. Run some more tests with varying modules and fields filtered etc. 

#### Context

High Priority - Unable to filter with multiple conditions using `OR` operator. This means the only way to achieve the same result is by making multiple calls (one for each option), which obviously increases overhead. 

#### Your Environment

* SuiteCRM Version used: 7.10.18
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): Postman v6
* Environment name and version (e.g. MySQL, PHP 7): PHP 7.1, 7.3
* Operating System and version (e.g Ubuntu 16.04): Ubuntu 16.04

### PR DESCRIPTION
**Pull request by serfreeman1337**
# Description
Issue reference: #8366 

Grouped out filter params for query.

## Motivation and Context
Without grouping we fail to apply OR filter.
Example of generated query:
```sql
contacts.phone_mobile = '...' OR contacts.phone_work = '...' OR contacts.deleted = '0'
```
Should be:
```sql
(contacts.phone_mobile = '...' OR contacts.phone_work = '...') AND contacts.deleted = '0'
```

## How To Test This
* Create a Contact and set Phone Work and Phone Mobile for some values.
* Apply OR filter to GET modules API call, targeting Contacts.
  ```
  /V8/module/Contacts?filter[operator]=or&filter[phone_mobile][eq]=some_value&filter[phone_work][eq]=some_value
  ```
* Run some more tests with varying filter value.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Api/V8/JsonApi/Repository/Filter.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4895293&bid=16211874)

File: Api/V8/JsonApi/Repository/Filter.php [hunk 1]
```diff
@@ -71,24 +78,20 @@ public function parseWhere(\SugarBean $bean, array $params)
...
-        return implode(sprintf(' %s ', $operator), $where);
-    }
-
-    /**
-     * Only return deleted records if they were explicitly requested
-     *
-     * @param array $params
-     * @return array
-     */
-    protected function addDeletedParameter(array $params)
```
Comment (Dillon-Brown) [inline Api/V8/JsonApi/Repository/Filter.php]: We wouldn't be able to remove this function in a minor version due to semVer / backwards compatibility. I would suggest to instead mark it as deprecated if it's no longer required.

**Comment by samus-aran** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Api/V8/JsonApi/Repository/Filter.php  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/samus-aran/SuiteCRM/pullRequest?prid=4895293&bid=16211874)

**Comment by Sl33pyDaemon** [comment]
Hi I do not know whether anyone is still active on this thread, but I sincerely hope there is somebody who could assist me. I am truly a huge fan of opensource and I am so grateful to the guys at SalesAgilty for SuiteCRM. I have to be honest though I have been using and implementing opensource software since 2006 and never have I ever had such a terrible time trying to figure out how things work as I do now with Suite. Can some body please tell me how do I define the Connection string and how do I configure the Auth on this? I have edited the Filter.php file and I have the XML Template loaded, but I just need to complete my connection to Suite

**Comment by serfreeman1337** [comment]
What do you mean by connection string ? 
You can check SutieCRM documentation, [JSON API](https://docs.suitecrm.com/developer/api/developer-setup-guide/json-api/) page shows how to configure and what can be done with the suitecrm http api. 

Complete "Before you start calling endpoints" part first, then create some client credentials on the "Admin ->  OAuth2 Clients and Tokens" page.

After that you can get your access token with following GET request:
```bash
curl -v \
-H 'Content-type: application/vnd.api+json' \
-H 'Accept: application/vnd.api+json' \
--data '{"grant_type":"client_credentials","client_id":"[UUID]","client_secret":"[SECRET]"}' \
http://[SUITECRM_INSTANCE]/Api/access_token
```
And then use it to access suitecrm api:
```bash
curl -i \
-H "Authorization: Bearer [TOKEN]" \
-H "Content-Type: application/json" \
http://[SUITECRM_INSTANCE]/Api/V8/module/Accounts?sort=-name
```
Also if it's not related to this pull request, you should ask on the [community forums](https://community.suitecrm.com/).

**Comment by Sl33pyDaemon** [comment]
Ok by connection string Im ean the Url I connect toI see you insert /Api for me and then access_token, so my connection string is http://hq.mygaway.co.za/Api/access_token . Is that correct?
I'm sorry to sound a little stupid but that is because I really am I suppose.
I'm really quite confused by the OAuth bit I will read those links you sent, but what I found funny though is that the log doesn't show any events "like it did when I did my AOP Config with Joomla" - when I run test which makes me thinks that the "Connection String" isn't quite right on my side.
I just put my site url in like "https://hq.mygaway.co.za"

**Comment by Sl33pyDaemon** [comment]
> Ok by connection string Im ean the Url I connect toI see you insert /Api for me and then access_token, so my connection string is http://hq.mygaway.co.za/Api/access_token . Is that correct? I'm sorry to sound a little stupid but that is because I really am I suppose. I'm really quite confused by the OAuth bit I will read those links you sent, but what I found funny though is that the log doesn't show any events "like it did when I did my AOP Config with Joomla" - when I run test which makes me thinks that the "Connection String" isn't quite right on my side. I just put my site url in like "https://hq.mygaway.co.za"

Argh Im an idiot, I have been so busy with this for so long I thought it was your XML. Sorry I must go back to the guy that referenced your fix and follow up with him.

**Review by jack7anderson7 — DISMISSED** [review]

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — DISMISSED** [review]
code looks ok

**Review by mattlorimer — APPROVED** [review]
