### PR TITLE
Fix #9728 - cron.php fails with "must be compatible" error

### LINKED ISSUE #9728: cron.php fails with "must be compatible" error from AOPInboundEmail.php
Trying to run cron.php fails with a warning:

    PHP Fatal error:  Declaration of AOPInboundEmail::handleCreateCase(Email $email, $userId) must be compatible with InboundEmail::handleCreateCase($email, $userId)

#### Issue

I installed SuiteCRM 8.1.2 in the environment described below. It appeared to do a legacy install even though everything went smoothly; I'm not sure whether that's expected. I ran public/legacy/cron.php manually and got the above fatal error.

#### Expected Behavior

cron.php can be run without errors

#### Actual Behavior

cron.php generated fatal error mentioned above

#### Possible Fix

I made this trivial change locally which allowed me to get around the issue. I'll open a pull request for it, though I'm not familiar enough with the code to know whether it's a good solution.

    --- a/modules/InboundEmail/AOPInboundEmail.php
    +++ b/modules/InboundEmail/AOPInboundEmail.php
    @@ -56,7 +56,7 @@ class AOPInboundEmail extends InboundEmail
         }
     
     
    -    public function handleCreateCase(Email $email, $userId)
    +    public function handleCreateCase($email, $userId)
         {
             global $current_user, $mod_strings, $current_language;
             $mod_strings = return_module_language($current_language, "Emails");

#### Steps to Reproduce

The issue was consistently reproducible in the environment described below. It's possible the issue only occurs with that PHP version or something else in the environment. I can give a detailed list of steps needed to install in that environment if needed.

#### Context

This prevents cron.php from running successfully in the environment below.

#### Your Environment

* SuiteCRM Version used: 8.1.2
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): n/a
* Environment name and version (e.g. MySQL, PHP 7):
  * MariaDB 10.5.16
  * PHP 8.0.21 (from remi repo, so IMAP support is built in)
  * Apache HTTP Server 2.4.54
  * PHP-FPM 8.0.22
* Operating System and version (e.g Ubuntu 16.04): Fedora 35

### PR DESCRIPTION
**Pull request by kgaillot**
… from AOPInboundEmail.php

## Description

Trying to run cron.php with PHP 8 fails with a fatal error (see [issue salesagility/SuiteCRM-Core#143](https://github.com/salesagility/SuiteCRM-Core/issues/143)):

    PHP Fatal error:  Declaration of AOPInboundEmail::handleCreateCase(Email $email, $userId) must be compatible with InboundEmail::handleCreateCase($email, $userId)

## Motivation and Context

This allows cron.php to succeed on a system with PHP 8.

The fix was suggested by pgr on forum team: "it’s a known issue that was aggravated in PHP 8 because it used to be a warning, now it’s FATAL"

## How To Test This
Run cron.php with PHP 8

(Note: for the script to fully succeed, PR salesagility/SuiteCRM#9731 for Issue salesagility/SuiteCRM#9730 must also be applied)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist
- [x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ ] My change requires a change to the documentation.
- [x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.

### CODE REVIEW

File: modules/InboundEmail/InboundEmail.php [hunk 1]
```diff
@@ -3607,7 +3607,7 @@ public function isMailBoxTypeCreateCase()
         return ($this->mailbox_type == 'createcase' && !empty($this->groupfolder_id));
     } // fn
 
-    public function handleCreateCase($email, $userId)
+    public function handleCreateCase(Email $email, $userId)
```
Comment (clemente-raposo) [inline modules/InboundEmail/InboundEmail.php:3610]: @jack7anderson7 in the scope of this change we should also cast the known calls to this method. To avoid getting the same issue in other places.

From a quick search I was able to find:
- tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php line 1727
- modules/Schedulers/_AddJobsHere.php line 666

Comment (jack7anderson7) [reply modules/InboundEmail/InboundEmail.php:3610]: Hi @kgaillot,

Following @clemente-raposo response, the call in `_AddJobsHere.php` on line 666. We believe a check should be added in, see below;

```php
 if (empty($aopInboundEmailX->email)){
   throw new Exception('Invalid Email Type');
 }
```

We can add this change in or, if you would like to add the check or something similar then feel free.

Thanks,
Jack

Comment (kgaillot) [reply modules/InboundEmail/InboundEmail.php:3610]: @clemente-raposo @jack7anderson7 Thanks, rebased on current hotfix branch and updated commit as suggested

**Review by jack7anderson7 — APPROVED** [review]

**Review by clemente-raposo — APPROVED** [review]
LGTM
